#ifndef _CS_DHCPS_TEST_CASE_H_
#define _CS_DHCPS_TEST_CASE_H_

#include "cs_testkit.h"

#ifdef __cplusplus
extern "C" {
#endif

CSUDI_BOOL CSTC_DHCPS_Init(void);
CSUDI_BOOL CSTC_DHCPS_UnInit(void);

CSUDI_BOOL CSTC_DHCPS_CSUDIDHCPSStartStop_0001(void);
CSUDI_BOOL CSTC_DHCPS_CSUDIDHCPSStartStop_0002(void);
CSUDI_BOOL CSTC_DHCPS_CSUDIDHCPSStartStop_0003(void);
CSUDI_BOOL CSTC_DHCPS_CSUDIDHCPSStartStop_0004(void);

CSUDI_BOOL CSTC_DHCPS_CSUDIDHCPSConfigGetConfig_0001(void);
CSUDI_BOOL CSTC_DHCPS_CSUDIDHCPSConfigGetConfig_0002(void);
CSUDI_BOOL CSTC_DHCPS_CSUDIDHCPSConfigGetConfig_0003(void);

CSUDI_BOOL CSTC_DHCPS_CSUDICSUDIDHCPSAddDelGetStaticIPCfg_0001(void);
CSUDI_BOOL CSTC_DHCPS_CSUDICSUDIDHCPSAddDelGetStaticIPCfg_0002(void);
CSUDI_BOOL CSTC_DHCPS_CSUDICSUDIDHCPSAddDelGetStaticIPCfg_0003(void);
CSUDI_BOOL CSTC_DHCPS_CSUDICSUDIDHCPSAddDelGetStaticIPCfg_0004(void);

CSUDI_BOOL CSTC_DHCPS_CSUDIDHCPSGetLeaseInfo_0001(void);
CSUDI_BOOL CSTC_DHCPS_CSUDIDHCPSGetLeaseInfo_0002(void);
CSUDI_BOOL CSTC_DHCPS_CSUDIDHCPSGetLeaseInfo_0003(void);


#ifdef __cplusplus
}
#endif

#endif
