#define		IDB_MAINMENU_LOGO				             102
#define		IDB_SUBMENU_FOCUS				             103
#define		IDB_SUBMENU_LOSE				             104
#define		IDB_MAINMENU_BOTTOM				             107
#define		IDB_MAINMENU_LEFT				             108
#define		IDB_MAINMENU_RIGHT				             109
#define		IDB_MAINMENU_TOP				             110
#define		IDB_SUBMENU_LOSE_ARROW				             113
#define		IDB_SUBMENU_FOCUS_ARROW				             114
#define		IDB_BOX_SEARCH				             120
#define		IDB_BOX_TV				             121
#define		IDB_BTN_BACK				             123
#define		IDB_BTN_EXIT				             125
#define		IDB_BTN_FAV				             126
#define		IDB_BTN_LEFTRIGHT				             128
#define		IDB_BTN_MENU				             129
#define		IDB_BTN_UPDOWN				             135
#define		IDB_DLG_BOTTOM				             157
#define		IDB_DLG_LEFT_LONG				             158
#define		IDB_DLG_LEFT_SHORT				             159
#define		IDB_DLG_RIGHT_LONG				             160
#define		IDB_DLG_RIGHT_SHORT				             161
#define		IDB_DLG_TOP				             162
#define		IDB_PGB_BLUE				             177
#define		IDB_PGB_GREEN				             178
#define		IDB_PGB_RED				             179
#define		IDB_SCROLLBAR_BOTTOM				             180
#define		IDB_SCROLLBAR_DOWN				             181
#define		IDB_SCROLLBAR_MIDDLE				             182
#define		IDB_SCROLLBAR_TOP				             183
#define		IDB_SCROLLBAR_UP				             184
#define		IDB_CHANNELLIST_BOTTOM				             201
#define		IDB_CHANNELLIST_LEFT				             202
#define		IDB_CHANNELLIST_RIGHT				             203
#define		IDB_CHANNELLIST_TOP				             204
#define		IDB_BOX_SEARCH2				             237
#define		IDB_BOX_SEARCH3				             238
#define		IDD_MAINMENU				             101
#define		IDC_MAINMENU_TOP				            1001
#define		IDC_MAINMENU_BOTTON				            1002
#define		IDC_MAINMENU_LEFT				            1003
#define		IDC_MAINMENU_LOGO				            1004
#define		IDC_MAINMENU_RIGHT				            1005
#define		IDC_MAINMENU_CAPTION				            1006
#define		IDC_MAINMENU_MENU				            1007
#define		IDC_MAINMENU_EXIT				            1008
#define		IDD_CHANNELSELECT				             207
#define		IDC_CHANNELSELECT_BMP_TOP				            1281
#define		IDC_CHANNELSELECT_BMP_LEFT				            1284
#define		IDC_CHANNELSELECT_BMP_RIGHT				            1285
#define		IDC_CHANNELSELECT_BMP_BOTTOM				            1286
#define		IDC_CHANNELSELECT_BMP_LOGO				            1282
#define		IDC_CHANNELSELECT_STATIC_TITLE				            1283
#define		IDC_CHANNELSELECT_BMP_HELP				            1625
#define		IDC_CHANNELSELECT_STATIC_HELP				            1624
#define		IDC_CHANNELSELECT_LIST_CHNNL				            1221
#define		IDD_SEARCH_MANUALSET				             205
#define		IDC_SMS_BMP_TOP				            1292
#define		IDC_SMS_BMP_LEFT				            1293
#define		IDC_SMS_BMP_RIGHT				            1294
#define		IDC_SMS_BMP_BOTTOM				            1295
#define		IDC_SMS_BMP_OK				            1296
#define		IDC_SMS_BMP_MENU				            1297
#define		IDC_SMS_BMP_BACK				            1584
#define		IDC_SMS_BMP_EXIT				            1298
#define		IDC_SMS_START				            1300
#define		IDC_SMS_CAPTION				            1299
#define		IDC_SMS_TXT_FREQUENCY				            1900
#define		IDC_SMS_TXT_SYMBOL				            1305
#define		IDC_SMS_TXT_MODULATION				            1306
#define		IDC_SMS_TXT_NIT				            1307
#define		IDC_SMS_EDIT_FREQUENCY				            2033
#define		IDC_SMS_EDIT_SYMBOL				            2034
#define		IDC_SMS_LRB_MODULATION				            1288
#define		IDC_SMS_LRB_NIT				            1289
#define		IDC_SMS_TXT_INTENSITY				            1302
#define		IDC_SMS_TXT_QUALITY				            1301
#define		IDC_SMS_PER_INTENSITY				            1303
#define		IDC_SMS_PER_QUALITY				            1304
#define		IDC_SMS_PGB_INTENSITY				            1290
#define		IDC_SMS_PGB_QUALITY				            1291
#define		IDD_SEARCH_SCANNING				             206
#define		IDC_SS_BMP_TOP				            1311
#define		IDC_SS_BMP_LEFT				            1313
#define		IDC_SS_BMP_RIGHT				            1314
#define		IDC_SS_BOTTOMBAR				            1321
#define		IDC_SS_BMP_BOTTOM				            1312
#define		IDC_SS_BMP_OK				            1315
#define		IDC_SS_BMP_MENU				            1316
#define		IDC_SS_BMP_BACK				            1585
#define		IDC_SS_BMP_EXIT				            1317
#define		IDC_SS_TOPBAR				            1320
#define		IDC_SS_OK				            1318
#define		IDC_SS_PER_PROGRESS				            1329
#define		IDC_SS_TXT_PROGRESS				            1328
#define		IDC_SS_BMP_SCANNING				            1327
#define		IDC_SS_CAPTION				            1319
#define		IDC_SS_RESULT				            1322
#define		IDC_SS_COUNT_TV				            1325
#define		IDC_SS_TXT_TV				            1323
#define		IDC_SS_COUNT_RADIO				            1326
#define		IDC_SS_TXT_RADIO				            1324
#define		IDC_SS_LIST				            1308
#define		IDC_SS_PGB_INTENSITY				            1309
#define		IDC_SS_PGB_QUALITY				            1310
#define		IDC_SS_TXT_INTENSITY				            1330
#define		IDC_SS_TXT_QUALITY				            1331
#define		IDC_SS_PER_INTENSITY				            1333
#define		IDC_SS_PER_QUALITY				            1332
#define		IDC_SS_LIST_STATUS				            1334
#define		IDS_SYS_MDFPWD_TITLE				            4003
#define		IDS_SYS_MDFPWD_NEWPWD1				            4004
#define		IDS_SUB_BTN1				            4005
#define		IDS_SUB_BTN2				            4006
#define		IDS_SUB_BTN3				            4007
#define		IDS_SUB_BTN4				            4008
#define		IDS_SUB_BTN5				            4009
#define		IDS_SUB_BTN6				            4010
#define		IDS_SUB_BTN21				            4011
#define		IDS_SUB_BTN22				            4012
#define		IDS_SUB_BTN31				            4013
#define		IDS_SUB_BTN32				            4014
#define		IDS_SUB_BTN41				            4015
#define		IDS_SYSMENUSET_TITLE				            4032
#define		IDS_SYSMENUSET_LANGUAGE				            4033
#define		IDS_SYSMENUSET_OPACITY				            4034
#define		IDS_SYSMENUSET_TIME				            4035
#define		IDS_SYS_MDFPWD_NEWPWD2				            4036
#define		IDS_SYS_VIDEOSET_TITLE				            4037
#define		IDS_SYSMOVE				            4038
#define		IDS_SYSSAVE				            4039
#define		IDS_SYS_VIDEOSET_TVMODE				            4040
#define		IDS_MAINMENU_TITLE_MAIN				            4041
#define		IDS_SYSMHP_STATIC_LOGO				            4042
#define		IDS_SYSANT_STATIC_TITLE				            4043
#define		IDS_SYSANT_STATIC_POWER				            4044
#define		IDS_SYSANTENNA_ON				            4045
#define		IDS_SYSANTENNA_OFF				            4046
#define		IDS_SYS_SCART_TV_CVBS				            4047
#define		IDS_MAINMENU_TITLE_SYSSET				            4048
#define		IDS_MAINMENU_TITLE_SCAN				            4049
#define		IDS_MAINMENU_TITLE_SYSINFO				            4050
#define		IDS_MAINMENU_TITLE_PRE				            4051
#define		IDS_SYS_VIDEOSET_SCREENMODE				            4052
#define		IDS_SYS_VIDEOSET_VIDEOSTYLE				            4053
#define		IDS_SYS_AUDIOSET_TITLE				            4054
#define		IDS_SYS_AUDIOSET_CHNNL				            4055
#define		IDS_SYS_AUDIOSET_PREF				            4056
#define		IDS_SYS_UHFSET_TITLE				            4057
#define		IDS_SYS_UHFSET_MODE				            4058
#define		IDS_SYS_UHFSET_CHNNL				            4059
#define		IDS_SYS_PASSWORD				            4060
#define		IDS_MSG_MDFPWD_FAIL				            4061
#define		IDS_MSG_MDFPWD_SUCC				            4062
#define		IDS_MSG_MDFPWD_TITLE				            4063
#define		IDS_SCHEDULE_NOTICE_CANCLE_TIMER				            4400
#define		IDS_SCHEDULE_NOTICE_SET_TIMER				            4401
#define		IDS_SCHEDULE_NOTICE_SAME_TIMER				            4402
#define		IDS_SCHEDULE_NOTICE_OK				            4403
#define		IDS_SCHEDULE_NOTICE_CANCLE				            4404
#define		IDS_CA_PAIR_CAPTION				            4405
#define		IDS_CA_PAIR_OK				            4406
#define		IDS_CA_PAIR_VERSION				            4407
#define		IDS_CA_PAIR_INPUTPWD				            4408
#define		IDS_CA_PAIR_STATUS				            4409
#define		IDS_CA_PAIR_STBID				            4410
#define		IDS_CA_ALARM_PAIRING_START				            4412
#define		IDS_CA_ALARM_SYSTEM_PAIRING				            4413
#define		IDS_CA_ALARM_SYSTEM_UPDATE				            4414
#define		IDS_CA_ALARM_SET_PASSWORDT				            4415
#define		IDS_MSG_INPUTPWD_TITLE				            4064
#define		IDS_MSG_UPGRADE_TITLE				            4065
#define		IDS_MSG_UPGRADE_MSG				            4066
#define		IDS_MSG_RSTDFLT_TITLE				            4067
#define		IDS_MSG_RSTDFLT_MSG				            4068
#define		IDS_MSG_OK				            4069
#define		IDS_MSG_EXIT				            4070
#define		IDS_MSG_INPUTPWD_WRONG				            4071
#define		IDS_SYS_AUDIOSET_CHNNL_LEFT				            4072
#define		IDS_SYS_AUDIOSET_CHNNL_RIGHT				            4073
#define		IDS_SYS_AUDIOSET_CHNNL_STEREO				            4074
#define		IDS_SYS_AUDIOSET_PREF_ARABIC				            4075
#define		IDS_SYS_AUDIOSET_PREF_ENGLISH				            4076
#define		IDS_SYS_AUDIOSET_PREF_FRENCH				            4077
#define		IDS_SYS_AUDIOSET_PREF_GERMAN				            4078
#define		IDS_SYS_AUDIOSET_PREF_SPANISH				            4079
#define		IDS_SYS_AUDIOSET_PREF_ITALIAN				            4080
#define		IDS_SYS_PRNTCTRL_TITLE				            4081
#define		IDS_SYS_PRNTCTRL_AGE				            4082
#define		IDS_INFO_CI_TITLE				            4083
#define		IDS_INFO_OK				            4084
#define		IDS_INFO_CHNNL_TITLE				            4085
#define		IDS_INFO_CHNNL_VIDEOPID				            4086
#define		IDS_INFO_CHNNL_AUDIOPID				            4087
#define		IDS_INFO_CHNNL_PCRPID				            4088
#define		IDS_INFO_CHNNL_TXTPID				            4089
#define		IDS_INFO_CHNNL_FREQ				            4090
#define		IDS_INFO_CHNNL_GUARD				            4091
#define		IDS_INFO_CHNNL_MODULATE				            4092
#define		IDS_INFO_CHNNL_LEVLE				            4093
#define		IDS_INFO_CHNNL_QUALITY				            4094
#define		IDS_CHEDIT_TITLE				            4095
#define		IDS_SYS_VIDEOSET_SCRMODE_4R3				            4160
#define		IDS_SYS_VIDEOSET_SCRMODE_16R9				            4161
#define		IDS_SYS_VIDEOSET_VIDSTYLE_PANSCAN				            4162
#define		IDS_SYS_VIDEOSET_VIDSTYLE_LETTERBOX				            4163
#define		IDS_SYS_VIDEOSET_VIDSTYLE_AUTO				            4164
#define		IDS_SYS_SCART_TV_RGB				            4165
#define		IDS_SYS_SCART_TV_S_VIDEO				            4166
#define		IDS_SYS_SCART_VCR_CVBS				            4167
#define		IDS_CHANNELSELECT_HELP				            4168
#define		IDS_SYS_VIDEOSET_TVMODE_AUTO				            4171
#define		IDS_MUPDATECHL_OKEXIT				            4172
#define		IDS_MUPDATECHL_UPDATE				            4173
#define		IDS_CHEDIT_SYMBRT				            4174
#define		IDS_CHEDIT_FREQ				            4175
#define		IDS_INFO_ACRDT_ID				            4177
#define		IDS_INFO_ACRDT_STARTTIME				            4178
#define		IDS_SYS_UHFSET_MODE_PAL_BG				            4179
#define		IDS_SYS_UHFSET_MODE_NTSC_M				            4180
#define		IDS_SYS_UHFSET_MODE_PAL_DK				            4181
#define		IDS_SYS_UHFSET_MODE_PAL_I				            4182
#define		IDS_INFO_ACRDT_ENDTIME				            4183
#define		IDS_CHEDIT_ALL				            4185
#define		IDS_MSG_SAVECHANGE_TITLE				            4191
#define		IDS_SYS_PRNTCTRL_AGE_NOLOCK				            4224
#define		IDS_SYS_PRNTCTRL_AGE_13				            4225
#define		IDS_SYS_PRNTCTRL_AGE_15				            4226
#define		IDS_SYS_PRNTCTRL_AGE_18				            4227
#define		IDS_SYS_PRNTCTRL_AGE_ALLLOCK				            4228
#define		IDS_CHEDIT_MUSIC				            4229
#define		IDS_CHEDIT_ART				            4230
#define		IDS_CHEDIT_SOCIETY				            4231
#define		IDS_CHEDIT_EDUCATION				            4232
#define		IDS_CHEDIT_EASE				            4233
#define		IDS_INFO_CI_VERSION1_NAME				            4301
#define		IDS_INFO_CI_VERSION2_NAME				            4302
#define		IDS_INFO_CI_PROVIDER1_NAME				            4303
#define		IDS_INFO_CI_PROVIDER2_NAME				            4304
#define		IDS_INFO_IRD_TITLE				            4307
#define		IDS_INFO_IRD_IRDTYPE_NAME				            4308
#define		IDS_INFO_IRD_IRDSERIAL_NAME				            4309
#define		IDS_INFO_IRD_HARDWAREVER_NAME				            4310
#define		IDS_INFO_IRD_SOFTWAREVER_NAME				            4311
#define		IDS_INFO_IRD_RELEASEDATA_NAME				            4312
#define		IDS_INFO_IRD_VERTYPE				            4319
#define		IDS_GUIDE_WEEK0				            4320
#define		IDS_GUIDE_WEEK1				            4321
#define		IDS_GUIDE_WEEK2				            4322
#define		IDS_GUIDE_WEEK3				            4323
#define		IDS_GUIDE_WEEK4				            4324
#define		IDS_GUIDE_WEEK5				            4325
#define		IDS_GUIDE_WEEK6				            4326
#define		IDS_GUIDE_MONTH1				            4327
#define		IDS_GUIDE_MONTH2				            4328
#define		IDS_GUIDE_MONTH3				            4329
#define		IDS_GUIDE_MONTH4				            4330
#define		IDS_GUIDE_MONTH5				            4331
#define		IDS_GUIDE_MONTH6				            4332
#define		IDS_GUIDE_MONTH7				            4334
#define		IDS_GUIDE_MONTH8				            4335
#define		IDS_GUIDE_MONTH9				            4336
#define		IDS_GUIDE_MONTH10				            4337
#define		IDS_GUIDE_MONTH11				            4338
#define		IDS_GUIDE_MONTH12				            4339
#define		IDS_GUIDE_UPDATING				            4340
#define		IDS_GUIDE_NOSERVICE				            4345
#define		IDS_SMS_CAPTION				            4346
#define		IDS_SMS_START				            4347
#define		IDS_SMS_FREQ				            4348
#define		IDS_SMS_NIT				            4351
#define		IDS_CHEDIT_SKIP				            4096
#define		IDS_CHEDIT_MOVE				            4097
#define		IDS_CHEDIT_LOCK				            4098
#define		IDS_CHEDIT_DELDTE				            4099
#define		IDS_STRING_NON				            4100
#define		IDS_INFO_ACRDT_TITLE				            4101
#define		IDS_CHEDIT_HELP_CHANGEGROUP				            4102
#define		IDS_CHFAV_TITLE				            4103
#define		IDS_CHFAV_ALL				            4104
#define		IDS_INFO_ACRDT_SN				            4105
#define		IDS_CHFAV_HELPSTA_CHANGEGROUP				            4106
#define		IDS_INFO_ACRDT_TYPE				            4107
#define		IDS_GUIDS_HELP_DATETIME				            4108
#define		IDS_GUIDE_HELP_PROLIST				            4109
#define		IDS_GUIDE_HELP_FAV				            4110
#define		IDS_GUIDE_HELP_DIGIT				            4111
#define		IDS_SMS_INTENSITY				            4352
#define		IDS_SMS_QUALITY				            4353
#define		IDS_SMS_QAM_16				            4354
#define		IDS_SMS_QAM_32				            4355
#define		IDS_SMS_QAM_64				            4356
#define		IDS_SMS_QAM_128				            4357
#define		IDS_SMS_NIT_OFF				            4358
#define		IDS_SMS_NIT_ON				            4359
#define		IDS_CHSEL_ALL				            4365
#define		IDS_SS_CAPTION				            4371
#define		IDS_SS_RESULT				            4372
#define		IDS_SS_PROGRESS				            4373
#define		IDS_SS_TV				            4374
#define		IDS_SS_RADIO				            4375
#define		IDS_SS_SEARCHING				            4376
#define		IDS_SS_SEARCHING_NIT				            4377
#define		IDS_SS_SEARCHING_FINISH				            4378
#define		IDS_SS_SKIP				            4379
#define		IDS_SS_INTENSITY				            4380
#define		IDS_SS_QUALITY				            4381
#define		IDS_SS_OK				            4382
#define		IDS_BARKER_SIGNAL_LOST				            4383
#define		IDS_GUIDE_HELP_MOVE				            4112
#define		IDS_GUIDE_CAPTION				            4113
#define		IDS_PROGRAMLIST_CAPTION				            4114
#define		IDS_PROGRAMLIST_SELECT				            4115
#define		IDS_PROGRAMLIST_MOVEFOCUS				            4116
#define		IDS_PROGRAMLIST_EXIT				            4117
#define		IDS_DATETIME_TIME1				            4118
#define		IDS_DATETIME_TIME2				            4119
#define		IDS_DATETIME_TIME3				            4120
#define		IDS_DATETIME_TIME4				            4121
#define		IDS_DATETIME_TIME5				            4122
#define		IDS_DATETIME_TIME6				            4123
#define		IDS_DATETIME_TIME7				            4124
#define		IDS_DATETIME_TIME8				            4125
#define		IDS_DATETIME_TIME9				            4126
#define		IDS_DATETIME_TIME10				            4127
#define		IDS_DATETIME_TIME11				            4128
#define		IDS_DATETIME_TIME12				            4129
#define		IDS_DATETIME_CAPTION				            4130
#define		IDS_DATETIME_SELECTDATE				            4131
#define		IDS_DATETIME_SELECTTIME				            4132
#define		IDS_INFOMAIL_LIST_TITLE				            4133
#define		IDS_INFOMAIL_LIST_ID				            4134
#define		IDS_INFOMAIL_LIST_TIME				            4135
#define		IDS_INFOMAIL_LIST_STATUS				            4136
#define		IDS_INFOMAIL_LIST_DELSEL				            4137
#define		IDS_INFOMAIL_LIST_DELALL				            4138
#define		IDS_INFOMAIL_LIST_MOV				            4139
#define		IDS_INFOMAIL_LIST_OK				            4140
#define		IDS_INFOMAIL_LIST_PAGE				            4141
#define		IDS_INFOMAIL_DETAIL_TITLE				            4142
#define		IDS_INFOMAIL_DETAIL_NAME				            4143
#define		IDS_INFOMAIL_DETAIL_FROM				            4144
#define		IDS_INFOMAIL_DETAIL_OK				            4145
#define		IDS_SCHEDULE_CAPTION				            4146
#define		IDS_SCHEDULE_NUMBER				            4147
#define		IDS_SCHEDULE_NAME				            4148
#define		IDS_SCHEDULE_DATE				            4149
#define		IDS_SCHEDULE_STARTIME				            4150
#define		IDS_SCHEDULE_ENDTIME				            4151
#define		IDS_SCHEDULE_HELP_MOVE				            4152
#define		IDS_SCHEDULE_HELP_OK				            4153
#define		IDS_MUPDATECHL_TITLE				            4154
#define		IDS_MUPDATECHL_REQUEST				            4155
#define		IDS_MUPDATECHL_SUCCESS				            4156
#define		IDS_MUPDATECHL_FAILED				            4157
#define		IDS_MUPDATECHL_OKREQUEST				            4158
#define		IDS_MUPDATECHL_EXIT				            4159
#define		IDS_MSG_SAVECHANGE_MSG				            4192
#define		IDS_PROGRAMLIST_NOEVENTNAME				            4193
#define		IDS_CA_ALARM_PAIRING_SIGNALLOST				            4194
#define		IDS_CA_ALARM_PAIRING_NOSMC				            4195
#define		IDS_CA_ALARM_PAIRING_INPAIRING				            4196
#define		IDS_CA_ALARM_PAIRING_INPAIRINGNOSMC				            4197
#define		IDS_CA_ALARM_PAIRING_ERROR_THREETIMES				            4198
#define		IDS_SMS_BAND_6				            4203
#define		IDS_SMS_BAND_7				            4204
#define		IDS_SMS_BAND_8				            4205
#define		IDS_CHSEL_FAV				            4206
#define		IDS_SMS_BAND				            4207
#define		IDS_BARKER_STILL_FRAME				            4398
#define		IDS_BARKER_NO_CHANNEL				            4399
#define		IDS_CA_ALARM_CHECK_PASSWORD				            4416
#define		IDS_CA_ALARM_WRITE_USER_INFO				            4417
#define		IDS_CA_ALARM_PAIRING_COMPLETE				            4418
#define		IDS_CA_ALARM_SMC_NOT_PAIRED				            4419
#define		IDS_CA_ALARM_NEGATIVE_TOKEN				            4420
#define		IDS_CA_ALARM_TOKEN_NOT_ENOUGH				            4421
#define		IDS_CA_ALARM_SUBSCRIPTION_EXPIRED				            4422
#define		IDS_CA_ALARM_SUCSCRIPTION_REMOVED				            4423
#define		IDS_CA_ALARM_STB_LOCKED				            4424
#define		IDS_CA_ALARM_PROGRAM_CHECKSUM_ERROR				            4425
#define		IDS_CA_ALARM_SMC_IN				            4426
#define		IDS_CA_ALARM_SMC_OUT				            4427
#define		IDS_CA_ALARM_SMC_ACCESS_ERROR				            4428
#define		IDS_CA_ALARM_SMC_ACCESS_OK				            4429
#define		IDS_CA_ALARM_DVN_CA				            4430
#define		IDS_CA_ALARM_OTHER				            4431
#define		IDS_SCHEDULE_PROGRAM_PLAY				            4433
#define		IDS_MAINMENU_TITLE_EPG				            4436
#define		IDS_MAINMENU_TITLE_MHP				            4437
#define		IDS_MAINMENU_TITLE_CHANNELSCAN				            4438
#define		IDS_MAINMENU_TITLE_PROGRAMMANAGE				            4439
#define		IDS_MAINMENU_TITLE_SYSTEMSETTING				            4440
#define		IDS_MAINMENU_TITLE_SYSTEMINFORMATION				            4441
#define		IDS_SYS_VIDEOSET_TVMODE_PAL				            4444
#define		IDS_SYS_VIDEOSET_TVMODE_NTSC				            4445
#define		IDS_SYS_SCART_VCR_S_VIDEO				            4447
#define		IDS_CHSEL_FILM				            4208
#define		IDS_CHSEL_NEWS				            4209
#define		IDS_CHSEL_GAMES				            4210
#define		IDS_CHSEL_SPORTS				            4211
#define		IDS_CHSEL_CHILDREN				            4212
#define		IDS_CHSEL_MUSIC				            4213
#define		IDS_CHSEL_ART				            4214
#define		IDS_CHSEL_SOCIETY				            4215
#define		IDS_CHSEL_EDUCATION				            4216
#define		IDS_CHSEL_EASE				            4217
#define		IDS_CHEDIT_FAV				            4218
#define		IDS_CHEDIT_FILM				            4219
#define		IDS_CHEDIT_NEWS				            4220
#define		IDS_CHEDIT_GAMES				            4221
#define		IDS_CHEDIT_SPORTS				            4222
#define		IDS_CHEDIT_CHILDREN				            4223
#define		IDS_SSN_TV				            4245
#define		IDS_SSN_RADIO				            4246
#define		IDS_SSN_RESULT1				            4247
#define		IDS_SSN_RESULT2				            4248
#define		IDS_SSN_RESULT3				            4249
#define		IDS_SSN_CAPTION				            4250
#define		IDS_SSN_PROGRESS				            4251
#define		IDS_SYS_AUDIOSET_SUBTITLE				            4252
#define		IDS_INFO_CHNNL_BANDWIDTH				            4253
#define		IDS_SYS_SCARTSET_TITLE				            4254
#define		IDS_SYS_SCARTSET_TVVIDEO				            4255
#define		IDS_SYS_SCARTSET_TVAUDIO				            4256
#define		IDS_SYS_VIDEOSET_LUM				            4257
#define		IDS_SYS_VIDEOSET_CHROMA				            4258
#define		IDS_SYS_VIDEOSET_CONTRAST				            4259
#define		IDS_SYS_SCARTSET_VCRVIDEO				            4260
#define		IDS_SYS_SCARTSET_VCRAUDIO				            4261
#define		IDS_SYS_SCARTSET_VIDEOOUTSEL_VIDEOMUTE				            4262
#define		IDS_SYS_SCARTSET_VIDEOOUTSEL_YCVBS_ENC				            4263
#define		IDS_SYS_SCARTSET_VIDEOOUTSEL_Y_ENC				            4264
#define		IDS_SYS_SCARTSET_VIDEOOUTSEL_YCVBS_VCR				            4265
#define		IDS_SYS_SCARTSET_VIDEOOUTSEL_CVBS_AUX				            4266
#define		IDS_SYS_SCARTSET_VIDEOOUTSEL_CVBS_TV				            4267
#define		IDS_SYS_SCARTSET_AUDIOOUTSEL_AUDIOMUTE				            4268
#define		IDS_SYS_SCARTSET_AUDIOOUTSEL_ENCORDER				            4269
#define		IDS_SYS_SCARTSET_AUDIOOUTSEL_VCR				            4270
#define		IDS_SYS_SCARTSET_AUDIOOUTSEL_AUX				            4271
#define		IDS_SYS_SCARTSET_AUDIOOUTSEL_TV				            4272
#define		IDS_SSN_INFO				            4273
#define		IDS_SS_NOSIGN				            4274
#define		IDS_SUB_BTN42				            4016
#define		IDS_SUB_BTN43				            4017
#define		IDS_SUB_BTN44				            4018
#define		IDS_SUB_BTN51				            4019
#define		IDS_SUB_BTN52				            4020
#define		IDS_SUB_BTN53				            4021
#define		IDS_SUB_BTN54				            4022
#define		IDS_SUB_BTN61				            4023
#define		IDS_SUB_BTN55				            4024
#define		IDS_SUB_BTN63				            4025
#define		IDS_MAINMENU_TITLE_PREFERENCE				            4026
#define		IDS_SUB_BTN62				            4027
#define		IDS_SYSMHP_ENABLE				            4028
#define		IDS_SYSMHP_DISABLE				            4029
#define		IDS_SYSMHP_TITLE				            4030
#define		IDS_SYSMHP_STATIC_BOOT				            4031
#define		IDS_SYS_SCART_TV_VCR				            4448
#define		IDS_MENULANG_ENGLISH				            4449
#define		IDS_MENULANG_FINNISH				            4450
#define		IDS_MENULANG_GERMAN				            4451
#define		IDS_MENULANG_ITALIAN				            4452
#define		IDS_MENULANG_SPANISH				            4453
#define		IDS_SYSANT_STATIC_GMT				            4460
#define		IDS_SYSANT_GMT_W1200				            4461
#define		IDS_SYSANT_GMT_W1100				            4462
#define		IDS_SYSANT_GMT_W1000				            4463
#define		IDS_SYSANT_GMT_W0900				            4464
#define		IDS_SYSANT_GMT_W0800				            4465
#define		IDS_SYSANT_GMT_W0700				            4466
#define		IDS_SYSANT_GMT_W0600				            4467
#define		IDS_SYSANT_GMT_W0500				            4468
#define		IDS_SYSANT_GMT_W0400				            4469
#define		IDS_SYSANT_GMT_W0330				            4470
#define		IDS_SYSANT_GMT_W0300				            4471
#define		IDS_SYSANT_GMT_W0200				            4472
#define		IDS_SYSANT_GMT_W0100				            4473
#define		IDS_SYSANT_GMT_0000				            4474
#define		IDS_SYSANT_GMT_E0100				            4475
#define		IDS_SYSANT_GMT_E0200				            4476
#define		IDS_SYSANT_GMT_E0300				            4477
#define		IDS_SYSANT_GMT_E0330				            4478
#define		IDS_SYSANT_GMT_E0400				            4479
#define		IDS_SYSANT_GMT_E0430				            4480
#define		IDS_SYSANT_GMT_E0500				            4481
#define		IDS_SYSANT_GMT_E0530				            4482
#define		IDS_SYSANT_GMT_E0545				            4483
#define		IDS_SYSANT_GMT_E0600				            4484
#define		IDS_SYSANT_GMT_E0630				            4485
#define		IDS_SYSANT_GMT_E0700				            4486
#define		IDS_SYSANT_GMT_E0800				            4487
#define		IDS_SYSANT_GMT_E0900				            4488
#define		IDS_SYSANT_GMT_E0930				            4489
#define		IDS_SYSANT_GMT_E1000				            4490
#define		IDS_SYSANT_GMT_E1100				            4491
#define		IDS_SYSANT_GMT_E1200				            4492
#define		IDS_SYSANT_GMT_E1300				            4493
#define		IDS_SYSANT_GMT_AUTO				            4494
#define		IDS_SUB_BTN56				            4500
#define		IDS_MUPDATE_CAPTION				            4600
#define		IDS_MUPDATE_SEARCH				            4601
#define		IDS_MUPDATE_INTENSITY				            4602
#define		IDS_MUPDATE_QUALITY				            4603
#define		IDS_MUPDATE_FREQ				            4604
#define		IDS_MUPDATE_MODE				            4605
#define		IDS_MUPDATE_GUARD				            4606
#define		IDS_MUPDATE_MODE_AUTO				            4607
#define		IDS_MUPDATE_MODE_2K				            4608
#define		IDS_MUPDATE_MODE_8K				            4609
#define		IDS_MUPDATE_GUARD_AUTO				            4610
#define		IDS_MUPDATE_GUARD_4				            4611
#define		IDS_MUPDATE_GUARD_8				            4612
#define		IDS_MUPDATE_GUARD_16				            4613
#define		IDS_MUPDATE_GUARD_32				            4614
#define		IDS_AUPDATE_SWITCH_YES				            4623
#define		IDS_UPGRADE_MSG_TITLE				            5000
#define		IDS_UPGRADE_MSG_START				            5001
#define		IDS_UPGRADE_MSG_CHANGE_TS				            5002
#define		IDS_UPGRADE_MSG_SEARCHING				            5003
#define		IDS_UPGRADE_MSG_NOT_FOUND				            5004
#define		IDS_UPGRADE_MSG_NOT_LOCK				            5005
#define		IDS_UPGRADE_MSG_NEED_UPGRADE				            5006
#define		IDS_UPGRADE_MSG_EXIT				            5007
#define		IDS_UPGRADE_MSG_CANCEL				            5008
#define		IDS_SYSMENUSET_TIME_ALWAYS				            5010
#define		IDS_SYSAUDIOSET_LRB_AUDIOPREF_WAITING				            5011
#define		IDS_SYSAUDIOSET_LRB_AUDIOPREF_UNKNOWN				            5012
#define		IDS_CHEDIT_HELP_OK				            5013
#define		IDS_AUDIOLANGUAGE_CHANGE				            5014
#define		IDS_MSG_ISP_WAIT_TITLE				            5020
#define		IDS_MSG_ISP_WAITING				            5021
#define		IDS_AUDIOLANGUAGE_TITLE				            5022
#define		IDS_SCHEDULE_NOTICE_FULL				            5023
#define		IDS_AUPDATE_SWITCH_NO				            4624
#define		IDS_AUPDATE_FRE_DAILY				            4625
#define		IDS_AUPDATE_FRE_WEEKLY				            4626
#define		IDS_AUPDATE_FRE_MONTHLY				            4627
#define		IDS_AUPDATE_STATIC_TITLE				            4628
#define		IDS_AUPDATE_STANDBY				            4629
#define		IDS_AUPDATE_MODE				            4630
#define		IDS_AUPDATE_TIME				            4631
#define		IDS_AUPDATE_FREQUENCY				            4632
#define		IDS_AUPDATE_FRE_ALWAYS				            4633
#define		IDS_SYSFB_TITLE				            4650
#define		IDS_SYSFB_STATIC_LANGUAGE				            4651
#define		IDS_SYSFB_STATIC_GMT				            4652
#define		IDS_SYSFB_STATIC_ANT				            4653
#define		IDS_SYSFBSEARCH				            4654
#define		IDS_INFO_CI_NO_MODULE				            4660
#define		IDS_INFOCI_SUB_TITLE				            4661
#define		IDS_INFOCI_SUB_NO_INFO				            4662
#define		IDS_INFOCI_SUB_EXIT				            4663
#define		IDS_INFOCI_SUB_UPDATE				            4664
#define		IDS_MMI_LIST_TITLE				            4670
#define		IDS_SMS_CHANNEL				            4700
#define		IDS_MSG_INPUTFREQ_TITLE				            4720
#define		IDS_MSG_INPUTFREQ_WRONG				            4721
#define		IDS_SUB_BTN45				            4722
#define		IDS_SYS_MODEM_TITLE				            4730
#define		IDS_SYS_MODEM_MODEM_TYPE				            4731
#define		IDS_SYS_MODEM_PHONE_PREFIX				            4732
#define		IDS_SYS_MODEM_DIALING				            4733
#define		IDS_SYS_MODEM_COUNTRY				            4734
#define		IDS_SYS_MODEM_MODEM_SPEED				            4735
#define		IDS_SYS_MODEM_ISP				            4736
#define		IDS_SYS_MODEM_MODEM_TYPE_INTERNAL				            4740
#define		IDS_SYS_MODEM_DIALING_TONE				            4745
#define		IDS_SYS_MODEM_DIALING_PULSE				            4746
#define		IDS_SYS_MODEM_COUNTRY_ITALY				            4750
#define		IDS_SYS_MODEM_MODEM_SPEED_LOW				            4755
#define		IDS_SYS_MODEM_MODEM_SPEED_HIGH				            4756
#define		IDS_SYS_ISP_TITLE				            4770
#define		IDS_SYS_ISP_DEFAULT_ISP				            4771
#define		IDS_SYS_ISP_PHONE_NUMBER				            4772
#define		IDS_SYS_ISP_USER_NAME				            4773
#define		IDS_SYS_ISP_PASSWORD				            4774
#define		IDS_SYS_ISP_DNS_SERVER				            4775
#define		IDS_SYS_ISP_DEFAULT_ISP_ENABLE				            4780
#define		IDS_SYS_ISP_DEFAULT_ISP_DISABLE				            4781
#define		IDS_MSG_DNS_TITLE				            4785
#define		IDS_MSG_DNS_WRONG				            4786
#define		IDS_KEYBOARD_TITLE_USERNAME				            4790
#define		IDS_KEYBOARD_TITLE_PASSWORD				            4791
#define		IDS_KEYBOARD_STATIC_USERNAME				            4792
#define		IDS_KEYBOARD_STATIC_PASSWORD				            4793
#define		IDS_KEYBOARD_CAPSON				            4794
#define		IDS_KEYBOARD_CAPSOFF				            4795
#define		IDS_WARNING_EXIT				            4800
#define		IDS_WARNING_OK				            4801
#define		IDS_MODULE_INITING				            4802
#define		IDS_REMOVE_SLOT1_INFO				            4803
#define		IDS_REMOVE_SLOT2_INFO				            4804
#define		IDS_INFOCI_UNKNOWNMODULE				            4805
#define		IDS_INFOCI_INITINGMODULE				            4806
#define		IDS_INFOCI_NOMODULE				            4807
#define		IDS_SYS_AUDIOSET_SUBTITLE_MANUAL				            5024
#define		IDS_SYS_AUDIOSET_SUBTITLE_AUTO				            5025
#define		IDS_SUBTITLESELECT_TITLE				            5026
#define		IDS_SUBTITLESELECT_CHANGE				            5027
#define		IDS_SUBTITLESELECT_OFF				            5028
#define		IDS_BARKER_INFO_NOTELETEXT				            5050
#define		IDS_SMS_SYMBOL				            5051
#define		IDS_SMS_MODULATION				            5052
