#include "cs_testkit.h"
#include "cs_smartcardtestentry.h"
#include "cs_smartcardtestcase.h"

/*begin change*/
static CSTestInit_S s_sTestInit = {CSTC_SMARTCARD_Init, CSTC_SMARTCARD_UnInit};
static CSTestCase_S s_asTestCase[] = 
{
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_GetCount_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_GetCount_0002)},//CS_TK_MANUALCASE，测试过程需与测试者交互
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Detect_0003)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Detect_0004)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetParam_0005)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetParam_0006)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetParam_0007)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetParam_0008)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetParam_0009)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetParam_0010)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetParam_0011)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetParam_0012)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetParam_0013)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetParam_0014)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_GetParam_0015)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_GetParam_0016)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_GetParam_0017)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Open_0018)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Open_0019)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Open_0020)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Close_0021)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Close_0022)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Close_0023)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Reset_0024)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Reset_0025)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Reset_0026)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Exchange_0027)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Exchange_0028)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Exchange_0029)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Exchange_0030)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Exchange_0031)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Exchange_0032)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Exchange_0033)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Send_0034)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Send_0035)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Send_0036)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Send_0037)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Send_0038)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Send_0039)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Receive_0040)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Receive_0041)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Receive_0042)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Receive_0043)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Receive_0044)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Receive_0045)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetPPS_0046)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetPPS_0047)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetPPS_0048)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetPPS_0049)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetPPS_0050)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Active_0051)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Active_0052)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Deactive_0053)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Deactive_0054)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_Detect_0055)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_SetParamGetParam_0056)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Open_0057)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_Open_0058)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Close_0059)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_Reset_0060)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_Reset_0061)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Reset_0062)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_Reset_0063)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_Reset_0064)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_Exchange_0065)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Exchange_0066)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Exchange_0067)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_Exchange_0068)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_Send_0069)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Send_0070)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SendReceice_0071)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_SetPPS_0072)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_SetPPS_0073)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_ActiveDeactive_0074)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_ActiveDeactive_0075)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_0076)},
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_0077)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_0078)},
	{CS_TK_AUTOCASE(CSTC_SMARTCARD_IT_Exchange_0079)},	
	{CS_TK_MANUALCASE(CSTC_SMARTCARD_IT_Exchange_0080)},	
	CS_TK_ENDCASE //测试用例结束标记，必须要有，且在最后一个
};

static CSTestGetObj_F s_afnTestGetObj[]= 
{
	CSSMARTCARDTESTGetObj,	//对应自己，必须是第一个，必须要有
};
/*end change*/

CS_TEST_BUILD_FRAME_CODE(SMARTCARD)
/*end don't change*/

