#ifndef _CS_SMARTCARD_TEST_CASE_H_
#define _CS_SMARTCARD_TEST_CASE_H_

#include "cs_testkit.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DEFINED_BOOL
typedef int              BOOL;
#define  DEFINED_BOOL
#endif

BOOL CSTC_SMARTCARD_Init(void);
BOOL CSTC_SMARTCARD_UnInit(void);

BOOL CSTC_SMARTCARD_IT_GetCount_0001(void);
BOOL CSTC_SMARTCARD_IT_GetCount_0002(void);
BOOL CSTC_SMARTCARD_IT_Detect_0003(void);
BOOL CSTC_SMARTCARD_IT_Detect_0004(void);
BOOL CSTC_SMARTCARD_IT_SetParam_0005(void);
BOOL CSTC_SMARTCARD_IT_SetParam_0006(void);
BOOL CSTC_SMARTCARD_IT_SetParam_0007(void);
BOOL CSTC_SMARTCARD_IT_SetParam_0008(void);
BOOL CSTC_SMARTCARD_IT_SetParam_0009(void);
BOOL CSTC_SMARTCARD_IT_SetParam_0010(void);
BOOL CSTC_SMARTCARD_IT_SetParam_0011(void);
BOOL CSTC_SMARTCARD_IT_SetParam_0012(void);
BOOL CSTC_SMARTCARD_IT_SetParam_0013(void);
BOOL CSTC_SMARTCARD_IT_SetParam_0014(void);
BOOL CSTC_SMARTCARD_IT_GetParam_0015(void);
BOOL CSTC_SMARTCARD_IT_GetParam_0016(void);
BOOL CSTC_SMARTCARD_IT_GetParam_0017(void);
BOOL CSTC_SMARTCARD_IT_Open_0018(void);
BOOL CSTC_SMARTCARD_IT_Open_0019(void);
BOOL CSTC_SMARTCARD_IT_Open_0020(void);
BOOL CSTC_SMARTCARD_IT_Close_0021(void);
BOOL CSTC_SMARTCARD_IT_Close_0022(void);
BOOL CSTC_SMARTCARD_IT_Close_0023(void);
BOOL CSTC_SMARTCARD_IT_Reset_0024(void);
BOOL CSTC_SMARTCARD_IT_Reset_0025(void);
BOOL CSTC_SMARTCARD_IT_Reset_0026(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0027(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0028(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0029(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0030(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0031(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0032(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0033(void);
BOOL CSTC_SMARTCARD_IT_Send_0034(void);
BOOL CSTC_SMARTCARD_IT_Send_0035(void);
BOOL CSTC_SMARTCARD_IT_Send_0036(void);
BOOL CSTC_SMARTCARD_IT_Send_0037(void);
BOOL CSTC_SMARTCARD_IT_Send_0038(void);
BOOL CSTC_SMARTCARD_IT_Send_0039(void);
BOOL CSTC_SMARTCARD_IT_Receive_0040(void);
BOOL CSTC_SMARTCARD_IT_Receive_0041(void);
BOOL CSTC_SMARTCARD_IT_Receive_0042(void);
BOOL CSTC_SMARTCARD_IT_Receive_0043(void);
BOOL CSTC_SMARTCARD_IT_Receive_0044(void);
BOOL CSTC_SMARTCARD_IT_Receive_0045(void);
BOOL CSTC_SMARTCARD_IT_SetPPS_0046(void);
BOOL CSTC_SMARTCARD_IT_SetPPS_0047(void);
BOOL CSTC_SMARTCARD_IT_SetPPS_0048(void);
BOOL CSTC_SMARTCARD_IT_SetPPS_0049(void);
BOOL CSTC_SMARTCARD_IT_SetPPS_0050(void);
BOOL CSTC_SMARTCARD_IT_Active_0051(void);
BOOL CSTC_SMARTCARD_IT_Active_0052(void);
BOOL CSTC_SMARTCARD_IT_Deactive_0053(void);
BOOL CSTC_SMARTCARD_IT_Deactive_0054(void);
BOOL CSTC_SMARTCARD_IT_Detect_0055(void);
BOOL CSTC_SMARTCARD_IT_SetParamGetParam_0056(void);
BOOL CSTC_SMARTCARD_IT_Open_0057(void);
BOOL CSTC_SMARTCARD_IT_Open_0058(void);
BOOL CSTC_SMARTCARD_IT_Close_0059(void);
BOOL CSTC_SMARTCARD_IT_Reset_0060(void);
BOOL CSTC_SMARTCARD_IT_Reset_0061(void);
BOOL CSTC_SMARTCARD_IT_Reset_0062(void);
BOOL CSTC_SMARTCARD_IT_Reset_0063(void);
BOOL CSTC_SMARTCARD_IT_Reset_0064(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0065(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0066(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0067(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0068(void);
BOOL CSTC_SMARTCARD_IT_Send_0069(void);
BOOL CSTC_SMARTCARD_IT_Send_0070(void);
BOOL CSTC_SMARTCARD_IT_SendReceice_0071(void);
BOOL CSTC_SMARTCARD_IT_SetPPS_0072(void);
BOOL CSTC_SMARTCARD_IT_SetPPS_0073(void);
BOOL CSTC_SMARTCARD_IT_ActiveDeactive_0074(void);
BOOL CSTC_SMARTCARD_IT_ActiveDeactive_0075(void);
BOOL CSTC_SMARTCARD_IT_0076(void);
BOOL CSTC_SMARTCARD_IT_0077(void);
BOOL CSTC_SMARTCARD_IT_0078(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0079(void);
BOOL CSTC_SMARTCARD_IT_Exchange_0080(void);
#ifdef __cplusplus
}
#endif

#endif

