#include "cs_testkit.h"
#include "cs_pcm_injectertestentry.h"
#include "cs_pcm_injectertestcase.h"

/*begin change*/
static CSTestInit_S s_sTestInit = {CSTC_PCM_INJECTER_Init, CSTC_PCM_INJECTER_UnInit};
static CSTestCase_S s_asTestCase[] = 
{
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_OpenClose_0001)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_OpenClose_0002)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_OpenClose_0003)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_OpenClose_0004)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_StartStop_0001)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_StartStop_0002)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_StartStop_0003)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_StartStop_0004)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_SetGetAttribute_0001)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_SetGetAttribute_0002)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_SetGetAttribute_0003)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_Flush_0001)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_Flush_0002)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_Clear_0001)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_Clear_0002)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_GetFreeBuffer_0001)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_WriteComplete_0001)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_WriteComplete_0002)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0001)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0002)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0003)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0004)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0005)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0006)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0007)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0008)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0009)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0010)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0011)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0012)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0013)},
	{CS_TK_AUTOCASE(CSTC_PCM_INJECTER_IT_INJECTER_0014)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0015)},	
		
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0016)},	
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0017)},	
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0018)},	
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0019)},	
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0020)},	
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0021)},	
    {CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0022)},
    {CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0023)},
	{CS_TK_MANUALCASE(CSTC_PCM_INJECTER_IT_INJECTER_0024)},

	CS_TK_ENDCASE //测试用例结束标记，必须要有，且在最后一个
};

static CSTestGetObj_F s_afnTestGetObj[]= 
{
	CSPCM_INJECTERTESTGetObj,	//对应自己，必须是第一个，必须要有
};
/*end change*/

CS_TEST_BUILD_FRAME_CODE(PCM_INJECTER)
/*end don't change*/

