#ifndef _CS_PCM_INJECTER_TEST_CASE_H_
#define _CS_PCM_INJECTER_TEST_CASE_H_

#include "cs_testkit.h"

#ifdef __cplusplus
extern "C" {
#endif

CSUDI_BOOL CSTC_PCM_INJECTER_Init(void);
CSUDI_BOOL CSTC_PCM_INJECTER_UnInit(void);

CSUDI_BOOL CSTC_PCM_INJECTER_IT_OpenClose_0001(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_OpenClose_0002(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_OpenClose_0003(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_OpenClose_0004(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_StartStop_0001(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_StartStop_0002(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_StartStop_0003(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_StartStop_0004(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_SetGetAttribute_0001(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_SetGetAttribute_0002(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_SetGetAttribute_0003(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_Flush_0001(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_Flush_0002(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_Clear_0001(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_Clear_0002(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_GetFreeBuffer_0001(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_WriteComplete_0001(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_WriteComplete_0002(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0001(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0002(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0003(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0004(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0005(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0006(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0007(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0008(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0009(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0010(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0011(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0012(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0013(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0014(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0015(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0016(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0017(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0018(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0019(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0020(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0021(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0022(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0023(void);
CSUDI_BOOL CSTC_PCM_INJECTER_IT_INJECTER_0024(void);

#ifdef __cplusplus
}
#endif

#endif

