#include "cs_testkit.h"
#include "cs_tunertestentry.h"

//#include "sub/cs_subtestentry.h" ///下级测试用例的目录

#include "cs_tunertestcase.h"

/*begin change*/
//static CSTestInit_S s_sTestInit = {CSUDI_NULL, CSUDI_NULL};
static CSTestInit_S s_sTestInit = {CSTC_TUNER_Init, CSTC_TUNER_UnInit};
static CSTestCase_S s_asTestCase[] = 
{
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetAllDeviceId_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetAllDeviceId_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetAllDeviceId_0003)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetAllDeviceId_0004)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetAllDeviceId_0005)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetDeviceInfo_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetDeviceInfo_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetDeviceInfo_0003)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddCallback_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddCallback_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddCallback_0003)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddCallback_0004)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddCallback_0005)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddCallback_0006)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddCallback_0007)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddCallback_0008)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddCallback_0009)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_DelCallback_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_DelCallback_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_DelCallback_0003)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_DelCallback_0004)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_DelCallback_0005)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddDelCallback_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddDelCallback_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0003)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0004)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0005)},
	{CS_TK_MANUALCASE(CSTC_TUNER_IT_Connect_0006)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0007)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0008)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0009)},
	{CS_TK_MANUALCASE(CSTC_TUNER_IT_Connect_0010)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0011)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0012)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0013)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0014)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0015)},
	{CS_TK_MANUALCASE(CSTC_TUNER_IT_Connect_0016)}, 
	{CS_TK_MANUALCASE(CSTC_TUNER_IT_Connect_0017)}, 
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0018)}, 
	{CS_TK_MANUALCASE(CSTC_TUNER_IT_Connect_0019)}, 
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_Connect_0020)}, 
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetSignalInfo_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetSignalInfo_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetSignalInfo_0003)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetSignalInfo_0004)},
//	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetSignalInfo_0005)},
	{CS_TK_MANUALCASE(CSTC_TUNER_IT_GetSignalInfo_0006)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetSignalInfo_0007)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_GetSignalInfo_0008)},
#if 0
	//注释掉中间件未使用的接口的测试
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddPID_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddPID_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddPID_0003)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RemovePID_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_AddRemovePID_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RDIAddCallback_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RDIAddCallback_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RDIAddCallback_0003)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RDIRemoveCallback_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RDIRemoveCallback_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RDIRemoveCallback_0003)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RDIRemoveCallback_0004)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RDI_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RDI_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_RDI_0003)},
#endif
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_UnifiedFreqTrans_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_QamConnectTime_0001)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_QamConnectTime_0002)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_QamConnectTime_0003)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_QamConnectTime_0004)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_QamConnectTime_0005)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_QamConnectTime_0006)},
	{CS_TK_AUTOCASE(CSTC_TUNER_IT_QamConnectTime_0007)},
	CS_TK_ENDCASE //测试用例结束标记，必须要有，且在最后一个
};


static CSTestGetObj_F s_afnTestGetObj[]= 
{
	CSTUNERTESTGetObj,	//对应自己，必须是第一个，必须要有
	//CSSUBTESTGetObj,	//下级测试用例目录入口，可以没有

};
/*end change*/

CS_TEST_BUILD_FRAME_CODE(TUNER)
/*end don't change*/

