#include "cs_testkit.h"
#include "cs_fstestentry.h"

//#include "sub/cs_subtestentry.h" ///下级测试用例的目录

#include "cs_fstestcase.h"

/*begin change*/
//static CSTestInit_S s_sTestInit = {CSUDI_NULL, CSUDI_NULL};
static CSTestInit_S s_sTestInit = {CSTC_FS_IT_Init, CSTC_FS_IT_UnInit};
static CSTestCase_S s_asTestCase[] = 
{
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIAddCallback_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRDIAddCallback_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIAddCallback_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIAddCallback_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIAddCallback_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIAddCallback_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIAddCallback_0007)},
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIRemoveCallback_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIRemoveCallback_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRDIRemoveCallback_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRDIRemoveCallback_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIRemoveCallback_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRDIRemoveCallback_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRDIRemoveCallback_0007)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIRemoveDev_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRDIRemoveDev_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRDIRemoveDev_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIRemoveDev_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSRDIRemoveDev_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSGetAllDeviceId_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSGetAllDeviceId_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetAllDeviceId_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetAllDeviceId_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetAllDeviceId_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetAllDeviceId_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetAllDeviceId_0007)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetAllDeviceId_0008)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0007)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0008)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0009)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0010)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0011)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0012)},
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSGetDeviceInfo_0013)},
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStandby_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStandby_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStandby_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStandby_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSWakeup_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSWakeup_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSWakeup_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSWakeup_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSFormat_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSFormat_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSFormat_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFormat_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSFormat_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSFormat_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSFormat_0007)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSFormat_0008)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0007)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0008)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0009)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0010)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0011)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpen_0012)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSOpen_0013)},
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRead_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRead_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRead_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRead_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRead_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRead_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRead_0007)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSWrite_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSWrite_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSWrite_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSWrite_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSWrite_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSClose_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSClose_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSClose_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0007)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0008)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0009)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0010)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0011)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0012)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSSeek_0013)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSLseek_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSLseek_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSLseek_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSLseek_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSLseek_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSLseek_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSTell_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSTell_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSTell_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSTell_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSLtell_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSLtell_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSLtell_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSLtell_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFlush_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFlush_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFlush_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRemove_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRemove_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRemove_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRemove_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRename_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRename_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRename_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRename_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRename_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRename_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRename_0007)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRename_0008)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRename_0009)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSTruncate_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSTruncate_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSTruncate_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSTruncate_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSTruncate_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFTruncate_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFTruncate_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFTruncate_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFTruncate_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFTruncate_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStat_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStat_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStat_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStat_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStat_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStat_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFstat_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFstat_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFstat_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFstat_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFstat_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFstat_0006)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSMkdir_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSMkdir_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSMkdir_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSMkdir_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSMkdir_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRmdir_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRmdir_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRmdir_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRmdir_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSRmdir_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpenDir_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpenDir_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpenDir_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSOpenDir_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSCloseDir_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSCloseDir_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSCloseDir_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSCloseDir_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSReadDir_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSReadDir_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSReadDir_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSReadDir_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSReadDir_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStatfs_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStatfs_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStatfs_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStatfs_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSStatfs_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_MANUALCASE(CSTC_FS_IT_CSUDIFSFstatfs_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFstatfs_0002)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFstatfs_0003)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFstatfs_0004)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_CSUDIFSFstatfs_0005)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_LongNameSupport_0001)},//CS_TK_AUTOCASE,测试过程无需干预
	{CS_TK_AUTOCASE(CSTC_FS_IT_FilePointCheck_0001)},
	{CS_TK_AUTOCASE(CSTC_FS_IT_LocalFsCheck)},
	{CS_TK_AUTOCASE(CSTC_FS_IT_LocalFsWriteRead_0001)},
	{CS_TK_AUTOCASE(CSTC_FS_IT_LocalFsWriteRead_0002)},
	{CS_TK_AUTOCASE(CSTC_FS_IT_LocalFsWriteRead_0003)},
	{CS_TK_AUTOCASE(CSTC_FS_IT_LocalFsWriteRead_0004)},
	{CS_TK_AUTOCASE(CSTC_FS_IT_0001)},
	CS_TK_ENDCASE //测试用例结束标记，必须要有，且在最后一个
};


static CSTestGetObj_F s_afnTestGetObj[]= 
{
	CSFSTESTGetObj,	//对应自己，必须是第一个，必须要有
	//CSSUBTESTGetObj,	//下级测试用例目录入口，可以没有

};
/*end change*/

CS_TEST_BUILD_FRAME_CODE(FS)
/*end don't change*/

