#ifndef _CS_FILE_TEST_CASE_H_
#define _CS_FILE_TEST_CASE_H_

#include "cs_testkit.h"

#ifdef __cplusplus
extern "C" {
#endif

CSUDI_BOOL CSTC_FILE_Init(void);
CSUDI_BOOL CSTC_FILE_UnInit(void);

CSUDI_BOOL CSTC_FILE_TEST_IT_CSUDIPLAYERProbe_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_Add_DelPlayerCallback_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_Add_DelPlayerCallback_0002(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_Add_DelPlayerCallback_0003(void);
CSUDI_BOOL CSTC_FILE_IT_CSUDIPLAYEROpenClose_0001(void);
CSUDI_BOOL CSTC_FILE_IT_CSUDIPLAYEROpenClose_0002(void);
CSUDI_BOOL CSTC_FILE_IT_CSUDIPLAYEROpenClose_0003(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_SetStream_GetPlaybackParam_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_SetStream_GetPlaybackParam_0002(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_StartStop_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_StartStop_0002(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_StartStop_0003(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_PauseResume_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_PauseResume_0002(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_PauseResume_0003(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_SetGetSpeed_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_SetGetSpeed_0002(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_Seek_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_GetCurPosInSec_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_GetDuration_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0002(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0003(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0004(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0005(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0006(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0007(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0008(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0009(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0010(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0011(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0012(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0013(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0014(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0015(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0016(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0017(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0018(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0019(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0020(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0021(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_0022(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_PlayToEnd_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_PlayToEnd_0002(void);
CSUDI_BOOL CSTC_FILE_TEST_CALLBACK_IT_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_CALLBACK_IT_0002(void);
CSUDI_BOOL CSTC_FILE_TEST_CALLBACK_IT_0003(void);
CSUDI_BOOL CSTC_FILE_TEST_CALLBACK_IT_0004(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_GetFileInfo_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_GetFileInfo_0002(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_GetFileInfo_0003(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_GetFileInfo_0004(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_GetFileInfo_0005(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_GetFileInfo_0005(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_GetFileInfo_0006(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_GetFileInfo_0007(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_SetFilePlayStream_0001(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_SetFilePlayStream_0002(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_SetFilePlayStream_0003(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_SetFilePlayStream_0004(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_SetFilePlayStream_0005(void);
CSUDI_BOOL CSTC_FILE_TEST_IT_SetFilePlayStream_0006(void);




#ifdef __cplusplus
}
#endif

#endif

