#include "cs_testkit.h"
#include "cs_filetestentry.h"
#include "cs_filetestcase.h"
//#include "sub/cs_subtestentry.h" ///下级测试用例的目录


/*begin change*/
//static CSTestInit_S s_sTestInit = {NULL, NULL};
static CSTestInit_S s_sTestInit = {CSTC_FILE_Init, CSTC_FILE_UnInit};
static CSTestCase_S s_asTestCase[] = 
{
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_CSUDIPLAYERProbe_0001)},

	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_Add_DelPlayerCallback_0001)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_Add_DelPlayerCallback_0002)},

	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_Add_DelPlayerCallback_0003)},
	{CS_TK_AUTOCASE(CSTC_FILE_IT_CSUDIPLAYEROpenClose_0001)},
	{CS_TK_AUTOCASE(CSTC_FILE_IT_CSUDIPLAYEROpenClose_0002)},
	{CS_TK_AUTOCASE(CSTC_FILE_IT_CSUDIPLAYEROpenClose_0003)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_SetStream_GetPlaybackParam_0001)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_SetStream_GetPlaybackParam_0002)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_StartStop_0001)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_StartStop_0002)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_StartStop_0003)},

	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_PauseResume_0001)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_PauseResume_0002)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_PauseResume_0003)},
	
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_SetGetSpeed_0001)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_SetGetSpeed_0002)}, 
	
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_Seek_0001)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_GetCurPosInSec_0001)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_GetDuration_0001)},

	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0001)},

	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0002)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0003)},

	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0004)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0005)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0006)},

	//{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0007)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0008)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0009)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0010)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0011)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0012)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0013)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0014)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0015)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0016)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0017)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0018)},

	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0019)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0020)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0021)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_0022)},

	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_PlayToEnd_0001)},
	{CS_TK_MANUALCASE(CSTC_FILE_TEST_IT_PlayToEnd_0002)},

	//{CS_TK_AUTOCASE(CSTC_FILE_TEST_CALLBACK_IT_0001)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_CALLBACK_IT_0002)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_CALLBACK_IT_0003)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_CALLBACK_IT_0004)},

	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_GetFileInfo_0001)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_GetFileInfo_0002)},
	
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_SetFilePlayStream_0001)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_SetFilePlayStream_0002)},
	{CS_TK_AUTOCASE(CSTC_FILE_TEST_IT_SetFilePlayStream_0003)},
	
	CS_TK_ENDCASE //测试用例结束标记，必须要有，且在最后一个
};


static CSTestGetObj_F s_afnTestGetObj[]= 
{
	CSFILETESTGetObj,	//对应自己，必须是第一个，必须要有
	//CSSUBTESTGetObj,	//下级测试用例目录入口，可以没有

};
/*end change*/

CS_TEST_BUILD_FRAME_CODE(FILE)
/*end don't change*/

