#ifndef _CS_INVOKENATIVE_TEST_CASE_H_
#define _CS_INVOKENATIVE_TEST_CASE_H_

#include "cs_testkit.h"

#ifdef __cplusplus
extern "C" {
#endif

BOOL CSTC_INVOKENATIVE_Init(void);
BOOL CSTC_INVOKENATIVE_UnInit(void);

BOOL CSTC_INVOKENATIVE_MT_0001(void);
BOOL CSTC_INVOKENATIVE_MT_0002(void);
BOOL CSTC_INVOKENATIVE_MT_0003(void);
BOOL CSTC_INVOKENATIVE_MT_0004(void);
BOOL CSTC_INVOKENATIVE_MT_0005(void);
BOOL CSTC_INVOKENATIVE_MT_0006(void);
BOOL CSTC_INVOKENATIVE_MT_0007(void);
BOOL CSTC_INVOKENATIVE_MT_0008(void);
BOOL CSTC_INVOKENATIVE_MT_0009(void);
BOOL CSTC_INVOKENATIVE_MT_0010(void);
BOOL CSTC_INVOKENATIVE_MT_0011(void);
BOOL CSTC_INVOKENATIVE_MT_0012(void);
BOOL CSTC_INVOKENATIVE_MT_0013(void);
BOOL CSTC_INVOKENATIVE_MT_0014(void);
BOOL CSTC_INVOKENATIVE_MT_0015(void);
BOOL CSTC_INVOKENATIVE_MT_0016(void);
BOOL CSTC_INVOKENATIVE_MT_0017(void);
BOOL CSTC_INVOKENATIVE_MT_0018(void);
BOOL CSTC_INVOKENATIVE_MT_0019(void);
BOOL CSTC_INVOKENATIVE_MT_0020(void);
BOOL CSTC_INVOKENATIVE_MT_0021(void);
BOOL CSTC_INVOKENATIVE_MT_0022(void);
BOOL CSTC_INVOKENATIVE_MT_0023(void);
BOOL CSTC_INVOKENATIVE_MT_0024(void);
BOOL CSTC_INVOKENATIVE_MT_0025(void);
BOOL CSTC_INVOKENATIVE_MT_0026(void);
BOOL CSTC_INVOKENATIVE_MT_0027(void);
BOOL CSTC_INVOKENATIVE_MT_0028(void);
BOOL CSTC_INVOKENATIVE_MT_0029(void);
BOOL CSTC_INVOKENATIVE_MT_0030(void);
BOOL CSTC_INVOKENATIVE_MT_0031(void);
BOOL CSTC_INVOKENATIVE_MT_0032(void);
BOOL CSTC_INVOKENATIVE_MT_0033(void);
BOOL CSTC_INVOKENATIVE_MT_0034(void);
BOOL CSTC_INVOKENATIVE_MT_0035(void);
BOOL CSTC_INVOKENATIVE_MT_0036(void);
BOOL CSTC_INVOKENATIVE_MT_0037(void);
BOOL CSTC_INVOKENATIVE_MT_0038(void);
BOOL CSTC_INVOKENATIVE_MT_0039(void);
BOOL CSTC_INVOKENATIVE_MT_0040(void);
BOOL CSTC_INVOKENATIVE_MT_0041(void);

#ifdef __cplusplus
}
#endif

#endif

