#ifndef _CS_RECORD_TEST_CASE_H_
#define _CS_RECORD_TEST_CASE_H_

#include "cs_testkit.h"

#ifdef __cplusplus
extern "C" {
#endif

CSUDI_BOOL CSTC_RECORD_Init(void);
CSUDI_BOOL CSTC_RECORD_UnInit(void);

CSUDI_BOOL CSTC_RECORD_IT_AddDelCallback_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_AddDelCallback_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_AddDelCallback_0003(void);
CSUDI_BOOL CSTC_RECORD_IT_AddDelCallback_0004(void);
CSUDI_BOOL CSTC_RECORD_IT_AddDelCallback_0005(void);
CSUDI_BOOL CSTC_RECORD_IT_OpenClose_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_OpenClose_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_OpenClose_0003(void);
CSUDI_BOOL CSTC_RECORD_IT_OpenClose_0004(void);
CSUDI_BOOL CSTC_RECORD_IT_StartStop_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_StartStop_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_StartStop_0003(void);
CSUDI_BOOL CSTC_RECORD_IT_GetSupportEncryptTypes_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_GetSupportEncryptTypes_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_GetRecTime_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_GetRecTime_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_GetRecTime_0003(void);
CSUDI_BOOL CSTC_RECORD_IT_FileCut_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_FileCut_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_ChnlRec_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_ChnlRec_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_TShiftRec_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_TShiftRec_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_TShiftRec_0003(void);
CSUDI_BOOL CSTC_RECORD_IT_TShiftRec_0004(void);
CSUDI_BOOL CSTC_RECORD_IT_TSRec_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_TSRec_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_Play_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_Play_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_Play_0003(void);
CSUDI_BOOL CSTC_RECORD_IT_Play_0004(void);
CSUDI_BOOL CSTC_RECORD_IT_Play_0005(void);
CSUDI_BOOL CSTC_RECORD_IT_Play_0006(void);
CSUDI_BOOL CSTC_RECORD_IT_Play_0007(void);
CSUDI_BOOL CSTC_RECORD_IT_Play_0008(void);
CSUDI_BOOL CSTC_RECORD_IT_Play_0009(void);
CSUDI_BOOL CSTC_RECORD_IT_0001(void);
CSUDI_BOOL CSTC_RECORD_IT_0002(void);
CSUDI_BOOL CSTC_RECORD_IT_0003(void);
CSUDI_BOOL CSTC_RECORD_IT_0004(void);
CSUDI_BOOL CSTC_RECORD_IT_0005(void);
CSUDI_BOOL CSTC_RECORD_IT_0006(void);
CSUDI_BOOL CSTC_RECORD_IT_0007(void);
CSUDI_BOOL CSTC_RECORD_IT_0008(void);
CSUDI_BOOL CSTC_RECORD_IT_0009(void);
CSUDI_BOOL CSTC_RECORD_IT_0010(void);
CSUDI_BOOL CSTC_RECORD_IT_0011(void);
CSUDI_BOOL CSTC_RECORD_IT_0012(void);
CSUDI_BOOL CSTC_RECORD_IT_0013(void);
CSUDI_BOOL CSTC_RECORD_IT_0014(void);
CSUDI_BOOL CSTC_RECORD_IT_0015(void);
CSUDI_BOOL CSTC_RECORD_IT_0016(void);
CSUDI_BOOL CSTC_RECORD_IT_0017(void);
CSUDI_BOOL CSTC_RECORD_IT_0018(void);
CSUDI_BOOL CSTC_RECORD_IT_0019(void);
CSUDI_BOOL CSTC_RECORD_IT_0020(void);
CSUDI_BOOL CSTC_RECORD_IT_0021(void);
CSUDI_BOOL CSTC_RECORD_IT_0022(void);
CSUDI_BOOL CSTC_RECORD_IT_0023(void);

#ifdef __cplusplus
}
#endif

#endif

