#include "cs_testkit.h"
#include "cs_ts_injectertestentry.h"
#include "cs_ts_injectertestcase.h"

/*begin change*/
//static CSTestInit_S s_sTestInit = {CSUDI_NULL, CSUDI_NULL};
static CSTestInit_S s_sTestInit = {CSTC_TS_INJECTER_Init, CSTC_TS_INJECTER_UnInit};
static CSTestCase_S s_asTestCase[] = 
{
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_OpenClose_0001)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_OpenClose_0002)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_OpenClose_0003)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_OpenClose_0004)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_StartStop_0001)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_StartStop_0002)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_StartStop_0003)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_StartStop_0004)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_SetGetAttribute_0001)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_SetGetAttribute_0002)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_SetGetAttribute_0003)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_Flush_0001)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_Flush_0002)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_Clear_0001)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_Clear_0002)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_GetFreeBuffer_0001)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_WriteComplete_0001)},
	{CS_TK_AUTOCASE(CSTC_TS_INJECTER_IT_WriteComplete_0002)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0001)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0002)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0003)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0004)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0005)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0006)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0007)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0008)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0009)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0010)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0011)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0012)},
    {CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0013)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0014)},
	{CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0015)},	
    {CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0016)}, 
    {CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0017)}, 
    {CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0018)},
    {CS_TK_MANUALCASE(CSTC_TS_INJECTER_IT_INJECTER_0019)},
	CS_TK_ENDCASE //测试用例结束标记，必须要有，且在最后一个
};

static CSTestGetObj_F s_afnTestGetObj[]= 
{
	CSTS_INJECTERTESTGetObj,	//对应自己，必须是第一个，必须要有
};
/*end change*/

CS_TEST_BUILD_FRAME_CODE(TS_INJECTER)
/*end don't change*/

