#ifndef _CS_SECTION_TEST_CASE_H_
#define _CS_SECTION_TEST_CASE_H_

#include "cs_testkit.h"
#include "udi2_typedef.h"
#ifdef __cplusplus
extern "C" {
#endif

CSUDI_BOOL CSTC_SECTION_Init(void);
CSUDI_BOOL CSTC_SECTION_UnInit(void);
CSUDI_BOOL CSTC_SECTION_IT_Allocate_0000(void);
CSUDI_BOOL CSTC_SECTION_IT_Allocate_0001(void);
CSUDI_BOOL CSTC_SECTION_IT_Allocate_0002(void);
CSUDI_BOOL CSTC_SECTION_IT_Allocate_0003(void);
CSUDI_BOOL CSTC_SECTION_IT_Allocate_0004(void);
CSUDI_BOOL CSTC_SECTION_IT_Allocate_0005(void);
CSUDI_BOOL CSTC_SECTION_IT_Allocate_0006(void);
CSUDI_BOOL CSTC_SECTION_IT_Start_0001(void);
CSUDI_BOOL CSTC_SECTION_IT_Start_0002(void);
CSUDI_BOOL CSTC_SECTION_IT_Start_0003(void);
CSUDI_BOOL CSTC_SECTION_IT_Stop_0001(void);
CSUDI_BOOL CSTC_SECTION_IT_Stop_0002(void);
CSUDI_BOOL CSTC_SECTION_IT_Stop_0003(void);
CSUDI_BOOL CSTC_SECTION_IT_Free_0001(void);
CSUDI_BOOL CSTC_SECTION_IT_Free_0002(void);
CSUDI_BOOL CSTC_SECTION_IT_Free_0003(void);
CSUDI_BOOL CSTC_SECTION_IT_Free_0004(void);
CSUDI_BOOL CSTC_SECTION_IT_Modify_0001(void);
CSUDI_BOOL CSTC_SECTION_IT_Modify_0002(void);
CSUDI_BOOL CSTC_SECTION_IT_Modify_0003(void);
CSUDI_BOOL CSTC_SECTION_IT_Modify_0004(void);
CSUDI_BOOL CSTC_SECTION_IT_SetBufSize_0001(void);
CSUDI_BOOL CSTC_SECTION_IT_SetBufSize_0002(void);
CSUDI_BOOL CSTC_SECTION_IT_0001(void);
CSUDI_BOOL CSTC_SECTION_IT_0002(void);
CSUDI_BOOL CSTC_SECTION_IT_0003(void);
CSUDI_BOOL CSTC_SECTION_IT_0004(void);
CSUDI_BOOL CSTC_SECTION_IT_0005(void);
CSUDI_BOOL CSTC_SECTION_IT_0006(void);
CSUDI_BOOL CSTC_SECTION_IT_0007(void);
CSUDI_BOOL CSTC_SECTION_IT_0008(void);
CSUDI_BOOL CSTC_SECTION_IT_0009(void);
CSUDI_BOOL CSTC_SECTION_IT_0010(void);
CSUDI_BOOL CSTC_SECTION_IT_0011(void);
CSUDI_BOOL CSTC_SECTION_IT_0012(void);
CSUDI_BOOL CSTC_SECTION_IT_0013(void);
CSUDI_BOOL CSTC_SECTION_IT_0014(void);
CSUDI_BOOL CSTC_SECTION_IT_0015(void);
CSUDI_BOOL CSTC_SECTION_IT_0016(void);
CSUDI_BOOL CSTC_SECTION_IT_0017(void);
CSUDI_BOOL CSTC_SECTION_IT_0018(void);
CSUDI_BOOL CSTC_SECTION_IT_0019(void);
CSUDI_BOOL CSTC_SECTION_IT_0020(void);
CSUDI_BOOL CSTC_SECTION_IT_0021(void);
CSUDI_BOOL CSTC_SECTION_IT_0022(void);
CSUDI_BOOL CSTC_SECTION_IT_0023(void);
CSUDI_BOOL CSTC_SECTION_IT_0024(void);
CSUDI_BOOL CSTC_SECTION_IT_0025(void);
CSUDI_BOOL CSTC_SECTION_IT_0026(void);
CSUDI_BOOL CSTC_SECTION_IT_0027(void);
CSUDI_BOOL CSTC_SECTION_IT_0028(void);
CSUDI_BOOL CSTC_SECTION_IT_0029(void);
CSUDI_BOOL CSTC_SECTION_IT_0030(void);
CSUDI_BOOL CSTC_SECTION_IT_0031(void);
CSUDI_BOOL CSTC_SECTION_IT_0032(void);
CSUDI_BOOL CSTC_SECTION_IT_0033(void);
CSUDI_BOOL CSTC_SECTION_IT_0034(void);
CSUDI_BOOL CSTC_SECTION_IT_0035(void);
CSUDI_BOOL CSTC_SECTION_IT_0036(void);
CSUDI_BOOL CSTC_SECTION_IT_0037(void);
CSUDI_BOOL CSTC_SECTION_IT_0038(void);
CSUDI_BOOL CSTC_SECTION_IT_0039(void);
CSUDI_BOOL CSTC_SECTION_IT_0040(void);
CSUDI_BOOL CSTC_SECTION_IT_0041(void);

#ifdef __cplusplus
}
#endif

#endif

