#include "cs_testkit.h"
#include "cs_sectiontestentry.h"
#include "cs_sectiontestcase.h"

/*begin change*/
static CSTestInit_S s_sTestInit = {CSTC_SECTION_Init, CSTC_SECTION_UnInit};
static CSTestCase_S s_asTestCase[] = 
{
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Allocate_0001)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Allocate_0002)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Allocate_0003)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Allocate_0004)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Allocate_0005)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Allocate_0006)},  
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Start_0001)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Start_0002)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Start_0003)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Stop_0001)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Stop_0002)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Stop_0003)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Free_0001)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Free_0002)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Free_0003)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Free_0004)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Modify_0001)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Modify_0002)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Modify_0003)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_Modify_0004)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_SetBufSize_0001)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_SetBufSize_0002)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0001)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0002)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0003)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0004)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0005)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0006)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0007)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0008)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0009)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0010)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0011)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0012)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0013)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0014)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0015)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0016)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0017)},
	//{CS_TK_AUTOCASE(CSTC_SECTION_IT_0018)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0019)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0020)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0021)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0022)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0023)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0024)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0025)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0026)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0027)},
	{CS_TK_MANUALCASE(CSTC_SECTION_IT_0028)},
	{CS_TK_MANUALCASE(CSTC_SECTION_IT_0029)},
	{CS_TK_MANUALCASE(CSTC_SECTION_IT_0030)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0031)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0032)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0033)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0034)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0035)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0036)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0037)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0038)},
	{CS_TK_MANUALCASE(CSTC_SECTION_IT_0039)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0040)},
	{CS_TK_AUTOCASE(CSTC_SECTION_IT_0041)},
	CS_TK_ENDCASE //测试用例结束标记，必须要有，且在最后一个
};


static CSTestGetObj_F s_afnTestGetObj[]= 
{
	CSSECTIONTESTGetObj,	//对应自己，必须是第一个，必须要有
};
/*end change*/

CS_TEST_BUILD_FRAME_CODE(SECTION)
/*end don't change*/

