#ifndef _CS_IPCFG_TEST_CASE_H_
#define _CS_IPCFG_TEST_CASE_H_

#include "cs_testkit.h"
#include "udi2_typedef.h"

#ifdef __cplusplus
extern "C" {
#endif


CSUDI_BOOL CSTC_IPCFG_Init(void);
CSUDI_BOOL CSTC_IPCFG_UnInit(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherCount_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherName_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherName_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherName_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherName_0004(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherName_0005(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherChipInfo_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherChipInfo_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherChipInfo_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherChipInfo_0004(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherChipInfo_0005(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetMacByName_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetMacByName_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetMacByName_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetMacByName_0004(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetMacByName_0005(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetMacByName_0006(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherStatus_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherStatus_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherStatus_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherStatus_0004(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherStatus_0005(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetEtherStatus_0006(void);
#ifdef PLATFORM_BCM7401
CSUDI_BOOL CSTC_IPCFG_IT_SearchAP_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_SearchAP_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_SearchAP_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_SearchAP_0004(void);
CSUDI_BOOL CSTC_IPCFG_IT_SearchAP_0005(void);
CSUDI_BOOL CSTC_IPCFG_IT_SearchAP_0006(void);
CSUDI_BOOL CSTC_IPCFG_IT_SearchAP_0007(void);
CSUDI_BOOL CSTC_IPCFG_IT_SearchAP_0008(void);
CSUDI_BOOL CSTC_IPCFG_IT_ConnectAP_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_ConnectAP_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_ConnectAP_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_ConnectAP_0004(void);
CSUDI_BOOL CSTC_IPCFG_IT_ConnectAP_0005(void);
CSUDI_BOOL CSTC_IPCFG_IT_ConnectAP_0006(void);
CSUDI_BOOL CSTC_IPCFG_IT_ConnectAP_0007(void);
CSUDI_BOOL CSTC_IPCFG_IT_ConnectAP_0008(void);
CSUDI_BOOL CSTC_IPCFG_IT_DisconnectAP_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_DisconnectAP_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetAPSignalQulityStrength_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetAPSignalQulityStrength_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetAPSignalQulityStrength_0003(void);
#endif
CSUDI_BOOL CSTC_IPCFG_IT_SetDNSServer_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetDNSServer_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetDNSServer_0004(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetDNSServer_0005(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetDNSServer_0006(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetDNSServer_0007(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetDNSServer_0008(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetDNSServer_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetDNSServer_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetDNSServer_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetDNSServer_0004(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetDNSServer_0005(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetIpInfo_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetIpInfo_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetIpInfo_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetIpInfo_0004(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetIpInfo_0005(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetIpInfo_0006(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetIpInfo_0007(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetIpInfo_0008(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetIpInfo_0009(void);
CSUDI_BOOL CSTC_IPCFG_IT_SetIpInfo_0010(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetIpInfo_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetIpInfo_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetIpInfo_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetIpInfo_0004(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetIpInfo_0005(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetStatInfo_0001(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetStatInfo_0002(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetStatInfo_0003(void);
CSUDI_BOOL CSTC_IPCFG_IT_GetStatInfo_0004(void);
CSUDI_BOOL CSTC_IPCFG_RAWSOCKET_0001(void);
CSUDI_BOOL CSTC_IPCFG_RAWSOCKET_0002(void);
CSUDI_BOOL CSTC_IPCFG_RAWSOCKET_0003(void);

#ifdef __cplusplus
}
#endif

#endif

