#include "cs_testkit.h"
#include "cs_ipcfgtestentry.h"
//#include "sub/cs_subtestentry.h" ///下级测试用例的目录

#include "cs_ipcfgtestcase.h"

/*begin change*/
//static CSTestInit_S s_sTestInit = {NULL, NULL};
static CSTestInit_S s_sTestInit = {CSTC_IPCFG_Init, CSTC_IPCFG_UnInit};
static CSTestCase_S s_asTestCase[] = 
{
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherCount_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherName_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherName_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherName_0003)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherName_0004)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherName_0005)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherChipInfo_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherChipInfo_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherChipInfo_0003)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherChipInfo_0004)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherChipInfo_0005)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetMacByName_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetMacByName_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetMacByName_0003)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetMacByName_0004)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetMacByName_0005)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetMacByName_0006)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherStatus_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherStatus_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherStatus_0003)},
	{CS_TK_MANUALCASE(CSTC_IPCFG_IT_GetEtherStatus_0004)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherStatus_0005)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetEtherStatus_0006)},
	#ifdef PLATFORM_BCM7401
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SearchAP_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SearchAP_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SearchAP_0003)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SearchAP_0004)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SearchAP_0005)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SearchAP_0006)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SearchAP_0007)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SearchAP_0008)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_ConnectAP_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_ConnectAP_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_ConnectAP_0003)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_ConnectAP_0004)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_ConnectAP_0005)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_ConnectAP_0006)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_ConnectAP_0007)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_ConnectAP_0008)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_DisconnectAP_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_DisconnectAP_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetAPSignalQulityStrength_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetAPSignalQulityStrength_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetAPSignalQulityStrength_0003)},
	#endif
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetDNSServer_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetDNSServer_0003)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetDNSServer_0004)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetDNSServer_0005)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetDNSServer_0006)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetDNSServer_0007)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetDNSServer_0008)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetDNSServer_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetDNSServer_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetDNSServer_0003)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetDNSServer_0004)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetDNSServer_0005)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetIpInfo_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetIpInfo_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetIpInfo_0003)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetIpInfo_0004)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetIpInfo_0005)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetIpInfo_0006)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetIpInfo_0007)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetIpInfo_0008)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetIpInfo_0009)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_SetIpInfo_0010)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetIpInfo_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetIpInfo_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetIpInfo_0003)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetIpInfo_0004)},	
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetIpInfo_0005)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetStatInfo_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetStatInfo_0002)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetStatInfo_0003)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_IT_GetStatInfo_0004)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_RAWSOCKET_0001)},
	{CS_TK_AUTOCASE(CSTC_IPCFG_RAWSOCKET_0002)},
	{CS_TK_MANUALCASE(CSTC_IPCFG_RAWSOCKET_0003)},


	CS_TK_ENDCASE //测试用例结束标记，必须要有，且在最后一个
};

static CSTestGetObj_F s_afnTestGetObj[]= 
{
	CSIPCFGTESTGetObj,	//对应自己，必须是第一个，必须要有
	//CSSUBTESTGetObj,	//下级测试用例目录入口，可以没有
};
/*end change*/

CS_TEST_BUILD_FRAME_CODE(IPCFG)
/*end don't change*/

