/******************************************************************************
FileName:  csmediaplayer.h
Copyright (c) 2007， Shen Zhen Coship Electronics CO.,LTD.。

Version:       Ver 1.0
Author:        liuzhenghua (liuzhenghua@coship.com)

File Description:
        This file is the message module of mediaplayer.

Modify History:
Version     Date        Author          Description
--------    ----------  --------        ------------

*******************************************************************************/

#ifndef CS_PLAYER_MESSAGE_H
#define CS_PLAYER_MESSAGE_H

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************
 *                                 Header File Include                         *
 ******************************************************************************/


/******************************************************************************
 *                                 Macro/Define/Structus                       *
 ******************************************************************************/
 
#define PUMP_MSG_START 		(0x0)
#define FILEPUMP_MSG_START  (0x0500)
#define MP_MSG_START 		(0x1000)
#define SEL_MSG_START 		(0x2000)
#define SEL_USERMSG_START 	(0x3000)
#define CSMPFFMPEGP_MSG_START (0x4000)
#define CSMPUDI2ADAPTERP_MSG_START (0x5000)

typedef enum _CSSELCallbackMessageType_E
{
    SEL_CONNECT_SUCCESS	= SEL_MSG_START	//连接数据源成功
    , SEL_CONNECT_FAILED		//连接数据源失败
    , SEL_PMT_VER_CHANGED	//PMT版本变化
    , SEL_PLAY_SUCCESS		//...3播放成功
    , SEL_STOP_SUCCESS		//停止播放成功
    , SEL_LOAD_SUCCESS		//...5 加载PAT、PMT成功
    , SEL_SERVICE_LOCKED	//节目加锁，未播放
    , SEL_PG_LOCKED			//pg锁,未播放
    , SEL_START_TO_TUNE   //...8
    , SEL_SERVICE_NOLOCK
    , SEL_NO_PROGRAME    //...a
    , SEL_CREATE_PATH_FAILED  //... b
    , SEL_SELECTION_SUCCESS //...c
    , SEL_FREQ_CHANGED  // 频点切换
    , SEL_SAME_LOCATOR
    , SEL_PLAY_READY// 15 准备播放
    , SEL_URL_INVALID
    , SEL_NIT_VER_CHANGED	//NIT版本变化
    , SEL_TUNNER_CONNECT_SUCCESS
    , SEL_TUNNER_CONNECT_FAILED
    , SEL_NOT_SUPPORT
}CSSELCallbackMessageType_E;  /*CSSelection发送回调类型*/


typedef enum CSMPMsg_E
{
    EM_CSMP_DECODER_SUCC = MP_MSG_START ,
    EM_CSMP_DECODER_FAIL,
    EM_CSMP_START_CA_SUCC,
    EM_CSMP_START_CA_FAIL,
    EM_CSMP_IPQAM_TOLIVE,
    EM_CSMP_AVPID_ZERO,
    EM_CSMP_FRONTTS_STOP,
    EM_CSMP_FRONTTS_RUN,
    EM_CSMP_NOT_SUPPORT,
    EM_CSMP_DECODER_STOPED,
    EM_CSMP_NEWFRAME_COMING,
    /*EM_CSMP_AVINFO_CHANGED消息收到后，如果第一个参数为0，
    则需要调用CSMPGetProgramInfo获取具体音视频信息，否则为实际音频类型*/
    EM_CSMP_AVINFO_CHANGED, 
    EM_CSMP_PMT_PARSE_SUCCESS,
    EM_CSMP_VOLUME_CHANGE,  /* 通知用户音量有调整dwPara1为当前音量值 */
    EM_CSMP_INVALID,
    EM_CSMP_STATE_CHANGED
}CSMPMsg_E;

/**@brief CSIPPUMPMsg_E  插件消息类型
[PUMP_MSG_START+0 ,PUMP_MSG_START+0x300)     插件通用消息
[PUMP_MSG_START+0x300 ,PUMP_MSG_START+0x500) 插件自定义消息
*/
typedef enum
{
    EM_CSIPPUMP_MSG_PAUSE_SUCC = PUMP_MSG_START,
    EM_CSIPPUMP_MSG_PAUSE_FAIL,
    EM_CSIPPUMP_MSG_RESUME_SUCC,
    EM_CSIPPUMP_MSG_RESUME_FAIL,
    EM_CSIPPUMP_MSG_SETRATE_SUCC,
    EM_CSIPPUMP_MSG_SETRATE_FAIL = PUMP_MSG_START + 5,
    EM_CSIPPUMP_MSG_SETTIME_SUCC,
    EM_CSIPPUMP_MSG_SETTIME_FAIL,
    EM_CSIPPUMP_MSG_PLAYDVB_SUCC,
    EM_CSIPPUMP_MSG_PLAYDVB_FAIL,
    EM_CSIPPUMP_MSG_SERVER_ERROR = PUMP_MSG_START + 10,
    EM_CSIPPUMP_MSG_SERVER_START_STREAM,
    EM_CSIPPUMP_MSG_SERVER_END_STREAM,
    EM_CSIPPUMP_MSG_SERVER_REDIRECT,
    EM_CSIPPUMP_MSG_SERVER_OPTIONS,
    EM_CSIPPUMP_MSG_SERVER_GETPARAMETER = PUMP_MSG_START + 15,
    EM_CSIPPUMP_MSG_SERVER_SETPARAMETER,
    EM_CSIPPUMP_MSG_DESCRIBE_SUCC,
    EM_CSIPPUMP_MSG_DESCRIBE_FAIL,
    EM_CSIPPUMP_MSG_SETUP_SUCC,
    EM_CSIPPUMP_MSG_SETUP_FAIL = PUMP_MSG_START + 20,
    EM_CSIPPUMP_MSG_AUTH_SUCC, //鉴权成功
    EM_CSIPPUMP_MSG_AUTH_FAIL, //鉴权失败
    EM_CSIPPUMP_MSG_SERVER_NODATA, //从服务器端收不到数据
    EM_CSIPPUMP_MSG_LIVE_TO_TIMESHIFT, //IPTV 直播到时移消息
    EM_CSIPPUMP_MSG_TIMESHIFT_TO_LIVE = PUMP_MSG_START + 25, //IPTV 直播到时移消息
    EM_CSIPPUMP_MSG_SAVE_BOOK_MARK,
    EM_CSIPPUMP_MSG_GET_START_TIME,
    EM_CSIPPUMP_MSG_CATVINFO_TOMP,
    EM_CSIPPUMP_MSG_SHAKEHAND_TIMEOUT, 
    EM_CSIPPUMP_MSG_CLEARBUFF= PUMP_MSG_START + 30, //TS注入播放清缓存
    EM_CSIPPUMP_MSG_NGOD_S1_SETUP,
    EM_CSIPPUMP_MSG_NGOD_S1_SETUP_TIMEOUT,
    EM_CSIPPUMP_MSG_NGOD_S1_PING,
    EM_CSIPPUMP_MSG_NGOD_S1_PING_TIMEOUT,
    EM_CSIPPUMP_MSG_NGOD_S1_TEARDOWN,
    EM_CSIPPUMP_MSG_NGOD_S1_TEARDOWN_TIMEOUT,
    EM_CSIPPUMP_MSG_NGOD_S1_ANNOUNCE,
    EM_CSIPPUMP_MSG_NGOD_C1_PLAY,
    EM_CSIPPUMP_MSG_NGOD_C1_PLAY_TIMEOUT,
    EM_CSIPPUMP_MSG_NGOD_C1_PAUSE,
    EM_CSIPPUMP_MSG_NGOD_C1_PAUSE_TIMEOUT,
    EM_CSIPPUMP_MSG_NGOD_C1_ANNOUNCE,
    EM_CSIPPUMP_MSG_NGOD_C1_GETPARAMETER,
    EM_CSIPPUMP_MSG_NGOD_C1_GETPARAMETER_TIMEOUT,
    EM_CSIPPUMP_MSG_NGOD_C1_SETPARAMETER,
    EM_CSIPPUMP_MSG_NGOD_C1_SETPARAMETER_TIMEOUT,
    EM_CSIPPUMP_MSG_INVALID 

}CSIPPUMPMsg_E;

typedef enum _CSFILEPUMPMsg_E
{
	EM_FILEPUMP_PLAYSUCC =FILEPUMP_MSG_START,//31(0X1F)本地mp3文件播放成功
	EM_FILEPUMP_PLAYFAIL,/*本地mp3文件播放失败*/
	EM_FILEPUMP_PLAYEND,   /*当前本地mp3文件播放完成*/
	EM_FILEPUMP_INVALIDFILE,/*播放文件非mp3格式*/
	EM_FILEPUMP_INTERRUPT, /*mp3播放中断,如拔掉U盘*/
	EM_FILEPUMP_FILEOPENFAIL,/*本地mp3文件打开失败*/
	EM_FILEPUMP_NOTSUPPORT,/*FILEPUMP暂不支持的功能*/
	EM_FILEPUMP_ERROR            /*FILEPUMP模块的错误（如读文件失败，解析URL失败等）*/
}CSFILEPUMPMsg_E;

typedef enum _CSMPFFMPEGMsg_E
{
	EM_CSMPFFMPEGP_MSG_PLAYEND = CSMPFFMPEGP_MSG_START,  //ffmpeg播放视频到结束位置消息
	EM_CSMPFFMPEGP_MSG_INVALID
}CSMPFFMPEGMsg_E;

typedef enum _CSMPUDI2ADAPTERMsg_E
{
	EM_CSMPUDI2ADAPTER_MSG_VIDEO_FRAME_COMING = CSMPUDI2ADAPTERP_MSG_START,  //UD2适配播放视频新帧消息
	EM_CSMPUDI2ADAPTER_MSG_AUDIO_FRAME_COMING,
	EM_CSMPUDI2ADAPTER_MSG_VIDEO_UNDERFLOW,
	EM_CSMPUDI2ADAPTER_MSG_AUDIO_UNDERFLOW,
	EM_CSMPUDI2ADAPTER_MSG_VIDEO_OVERFLOW,
	EM_CSMPUDI2ADAPTER_MSG_AUDIO_OVERFLOW,
	EM_CSMPUDI2ADAPTER_MSG_VIDEO_SOURCE_CHANGE,
	EM_CSMPUDI2ADAPTER_MSG_AUDIO_SOURCE_CHANGE,
	EM_CSMPUDI2ADAPTER_MSG_END_OF_STREAM,
	EM_CSMPUDI2ADAPTER_MSG_BEGIN_OF_STREAM,
	EM_CSMPUDI2ADAPTER_MSG_ERR_ABORTED,
	EM_CSMPUDI2ADAPTER_MSG_ERR_DECODE,
	EM_CSMPUDI2ADAPTER_MSG_ERR_FORMAT,
	EM_CSMPUDI2ADAPTER_MSG_ERR_SEEK,
	EM_CSMPUDI2ADAPTER_MSG_ERR_PAUSE,
	EM_CSMPUDI2ADAPTER_MSG_ERR_RESUME,
	EM_CSMPUDI2ADAPTER_MSG_ERR_SETSPEED,
	EM_CSMPUDI2ADAPTER_MSG_ERR_NETWORK,
	EM_CSMPUDI2ADAPTER_MSG_ERR_TIMEOUT,
	EM_CSMPUDI2ADAPTER_MSG_STATE_LOADING,
	EM_CSMPUDI2ADAPTER_MSG_STATE_LOADED,
	EM_CSMPUDI2ADAPTER_MSG_STATE_HAVEMETADATA,
	EM_CSMPUDI2ADAPTER_MSG_STATE_ENOUGHDATA_FORPLAY,
	EM_CSMPUDI2ADAPTER_MSG_STATE_DURATIONCHANGE,
	EM_CSMPUDI2ADAPTER_MSG_STATE_RATECHANGE,
	EM_CSMPUDI2ADAPTER_MSG_STATE_LOADING_PROGRESS,
	EM_CSMPUDI2ADAPTER_MSG_STATE_LOADING_DOWNLOADRATE,
	EM_CSMPUDI2ADAPTER_MSG_STATE_STOP,
	EM_CSMPUDI2ADAPTER_MSG_STATE_START,
	EM_CSMPUDI2ADAPTER_MSG_STATE_PAUSE,
	EM_CSMPUDI2ADAPTER_MSG_SEEK_FINISH,
	EM_CSMPUDI2ADAPTER_MSG_SHOW_SUBTITLE,
	EM_CSMPUDI2ADAPTER_MSG_CLEAR_SUBTITLE,
	EM_CSMPUDI2ADAPTER_MSG_INVALID
}CSMPUDI2ADAPTERMsg_E;

#ifdef __cplusplus
}
#endif

#endif  /* CSMP_H */
