#ifndef _CS_AOUT_TEST_CASE_H_
#define _CS_AOUT_TEST_CASE_H_

#include "cs_testkit.h"

#ifdef __cplusplus
extern "C" {
#endif

CSUDI_BOOL CSTC_AOUT_Init(void);
CSUDI_BOOL CSTC_AOUT_UnInit(void);

CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTMute_0001( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTMute_0002( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTMute_0003( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTMute_0004( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTMute_0005( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTMute_0006( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTUnmute_0001( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTUnmute_0002( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTUnmute_0003( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTUnmute_0004( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTUnmute_0005( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTUnmute_0006( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTUnmute_0007( void );
CSUDI_BOOL CSTC_AOUT_TEST_IT_AOUTUnmute_0008( void );
CSUDI_BOOL CSTC_AOUT_SetOPMode_0001( void );
CSUDI_BOOL CSTC_AOUT_SetOPMode_0002(void);
CSUDI_BOOL CSTC_AOUT_SetOPMode_0003(void);
CSUDI_BOOL CSTC_AOUT_SetOPMode_0004(void);
CSUDI_BOOL CSTC_AOUT_SetOPMode_0005(void);
CSUDI_BOOL CSTC_AOUT_SetOPMode_0006(void);

#ifdef __cplusplus
}
#endif

#endif

