#ifndef _CS_DESCRAMBLE_TEST_CASE_H_
#define _CS_DESCRAMBLE_TEST_CASE_H_

#include "cs_testkit.h"

#ifdef __cplusplus
extern "C" {
#endif

CSUDI_BOOL CSTC_DESCRAMBLE_Init(void);
CSUDI_BOOL CSTC_DESCRAMBLE_UnInit(void);

CSUDI_BOOL CSTC_DSM_TEST_IT_DSMAllocate_0001( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMAllocate_0002( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMAllocate_0003( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMAllocate_0004( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMAllocate_0005( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMFree_0001( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMFree_0002( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_SMSetPID_0001( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_SMSetPID_0002( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_SMSetPID_0003( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_SMClearPID_0001( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_SMClearPID_0002( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMSetOddKey_0001( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMSetOddKey_0002( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMSetOddKey_0003( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMSetEvenKey_0001( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMSetEvenKey_0002( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMSetEvenKey_0003( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_DSMSetKey_0001( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_Descramble_0001( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_Descramble_0002( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_Descramble_0003( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_Descramble_0004( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_Descramble_0005( void );
CSUDI_BOOL CSTC_DSM_TEST_IT_Descramble_0006( void );

#ifdef __cplusplus
}
#endif

#endif

