#include "cs_testkit.h"
#include "cs_descrambletestentry.h"
#include "cs_descrambletestcase.h"

/*begin change*/
static CSTestInit_S s_sTestInit = {CSTC_DESCRAMBLE_Init, CSTC_DESCRAMBLE_UnInit};
static CSTestCase_S s_asTestCase[] = 
{
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMAllocate_0001)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMAllocate_0002)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMAllocate_0003)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMAllocate_0004)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMAllocate_0005)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMFree_0001)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMFree_0002)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_SMSetPID_0001)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_SMSetPID_0002)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_SMSetPID_0003)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_SMClearPID_0001)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_SMClearPID_0002)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMSetOddKey_0001)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMSetOddKey_0002)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMSetOddKey_0003)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMSetEvenKey_0001)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMSetEvenKey_0002)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMSetEvenKey_0003)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_DSMSetKey_0001)},
	{CS_TK_MANUALCASE(CSTC_DSM_TEST_IT_Descramble_0001)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_Descramble_0002)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_Descramble_0003)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_Descramble_0004)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_Descramble_0005)},
	{CS_TK_AUTOCASE(CSTC_DSM_TEST_IT_Descramble_0006)},
	CS_TK_ENDCASE //测试用例结束标记，必须要有，且在最后一个
};


static CSTestGetObj_F s_afnTestGetObj[]= 
{
	CSDESCRAMBLETESTGetObj,	//对应自己，必须是第一个，必须要有
};
/*end change*/

CS_TEST_BUILD_FRAME_CODE(DESCRAMBLE)
/*end don't change*/

