#ifndef _CS_AP_TEST_CASE_H_
#define _CS_AP_TEST_CASE_H_

#include "cs_testkit.h"

#ifdef __cplusplus
extern "C" {
#endif

CSUDI_BOOL CSTC_AP_Init(void);
CSUDI_BOOL CSTC_AP_UnInit(void);

CSUDI_BOOL CSTC_AP_SetSignal_0001(void);
CSUDI_BOOL CSTC_AP_SetSignal_0002(void);
CSUDI_BOOL CSTC_AP_SetSignal_0003(void);


CSUDI_BOOL CSTC_AP_SetFreqChannel_0001(void);
CSUDI_BOOL CSTC_AP_SetFreqChannel_0002(void);


CSUDI_BOOL CSTC_AP_SetSSIDSeparate_0001(void);
CSUDI_BOOL CSTC_AP_SetSSIDSeparate_0002(void);


CSUDI_BOOL CSTC_AP_GetConfig_0001(void);
CSUDI_BOOL CSTC_AP_GetConfig_0002(void);


CSUDI_BOOL CSTC_AP_GetSSIDCapblitity_0001(void);
CSUDI_BOOL CSTC_AP_GetSSIDCapblitity_0002(void);

CSUDI_BOOL CSTC_AP_GetSSIDs_0001(void);
CSUDI_BOOL CSTC_AP_GetSSIDs_0002(void);
CSUDI_BOOL CSTC_AP_GetSSIDs_0003(void);


CSUDI_BOOL CSTC_AP_SetSSIDs_0001(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0002(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0003(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0004(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0005(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0006(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0007(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0008(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0009(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0010(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0011(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0012(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0013(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0014(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0015(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0016(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0017(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0018(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0019(void);
CSUDI_BOOL CSTC_AP_SetSSIDs_0020(void);


CSUDI_BOOL CSTC_AP_GetStationsInfo_0001(void);
CSUDI_BOOL CSTC_AP_GetStationsInfo_0002(void);
CSUDI_BOOL CSTC_AP_GetStationsInfo_0003(void);
CSUDI_BOOL CSTC_AP_GetStationsInfo_0004(void);
CSUDI_BOOL CSTC_AP_GetStationsInfo_0005(void);


CSUDI_BOOL CSTC_AP_SetGetAdvancedInfo_0001(void);
CSUDI_BOOL CSTC_AP_SetGetAdvancedInfo_0002(void);
CSUDI_BOOL CSTC_AP_SetGetAdvancedInfo_0003(void);
CSUDI_BOOL CSTC_AP_SetGetAdvancedInfo_0004(void);
CSUDI_BOOL CSTC_AP_SetGetAdvancedInfo_0005(void);
CSUDI_BOOL CSTC_AP_SetGetAdvancedInfo_0006(void);
CSUDI_BOOL CSTC_AP_SetGetAdvancedInfo_0007(void);
CSUDI_BOOL CSTC_AP_SetGetAdvancedInfo_0008(void);


#ifdef __cplusplus
}
#endif

#endif

