#ifndef _CS_EEPROM_TEST_CASE_H_
#define _CS_EEPROM_TEST_CASE_H_

#include "cs_testkit.h"
#include "udi2_eeprom.h"
#include "cs_eepromudi2_test.h"

#ifdef __cplusplus
extern "C" {
#endif

CSUDI_BOOL  CSTC_EEPROM_Init(void);
CSUDI_BOOL  CSTC_EEPROM_UnInit(void);

CSUDI_BOOL  CSTC_EEPROM_IT_EPRGetInfo_0001(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRGetInfo_0002(void);

CSUDI_BOOL  CSTC_EEPROM_IT_EPRWrite_0001(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWrite_0002(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWrite_0003(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWrite_0004(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWrite_0005(void);


CSUDI_BOOL  CSTC_EEPROM_IT_EPRRead_0001(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRRead_0002(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRRead_0003(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRRead_0004(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRRead_0005(void);

CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0001(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0002(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0003(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0004(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0005(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0006(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0007(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0008(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0009(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0010(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0011(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0012(void);
CSUDI_BOOL  CSTC_EEPROM_IT_EPRWriteRead_0013(void);
#ifdef __cplusplus
}
#endif

#endif

