#ifndef _CS_BOOTSHOW_TEST_CASE_H_
#define _CS_BOOTSHOW_TEST_CASE_H_

#include "cs_testkit.h"

#ifdef __cplusplus
extern "C" {
#endif

BOOL CSTC_BOOTSHOW_Init(void);
BOOL CSTC_BOOTSHOW_UnInit(void);

BOOL CSTC_BOOTSHOW_MT_0001(void);
BOOL CSTC_BOOTSHOW_MT_0002(void);

CSUDI_BOOL CSTC_BOOTSHOW_GetUnitCount_0001(void);
CSUDI_BOOL CSTC_BOOTSHOW_GetUnitCount_0002(void);

CSUDI_BOOL CSTC_BOOTSHOW_GetCapability_0001(void);
CSUDI_BOOL CSTC_BOOTSHOW_GetCapability_0002(void);

CSUDI_BOOL CSTC_BOOTSHOW_GetShowUnitInfo_0001(void);
CSUDI_BOOL CSTC_BOOTSHOW_GetShowUnitInfo_0002(void);
CSUDI_BOOL CSTC_BOOTSHOW_GetShowUnitInfo_0003(void);

CSUDI_BOOL CSTC_BOOTSHOW_GetFreeSize_0001(void);
CSUDI_BOOL CSTC_BOOTSHOW_GetFreeSize_0002(void);
CSUDI_BOOL CSTC_BOOTSHOW_GetFreeSize_0003(void);

CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0001(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0002(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0003(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0004(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0005(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0006(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0007(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0008(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0009(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0010(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0011(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0012(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0013(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0014(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetShowUnitInfo_0015(void);

CSUDI_BOOL CSTC_BOOTSHOW_SetNeedShow_0001(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetNeedShow_0002(void);
CSUDI_BOOL CSTC_BOOTSHOW_SetNeedShow_0003(void);

#ifdef __cplusplus
}
#endif

#endif

